### PR TITLE
Add alternate Bound Diamond recipe

### PR DESCRIPTION
**Pull request by xSkewer**
image
Alternative to the binding ritual for Bound Diamonds.

### CODE REVIEW

**Review by Connor-Colenso — APPROVED** [review]

**Comment by Dream-Master** [comment]
What was the original recipe ?

**Comment by xSkewer** [comment]
image
I haven't done a binding ritual in a while so I'm not sure what other costs are part of it.

**Comment by Connor-Colenso** [comment]
This is an alternative more expensive recipe using the altar, discussed in #general on discord.

**Comment by Dream-Master** [comment]
Ok

**Comment by DianeXD** [comment]
exquisite diamond => blood diamond
tier4 12000lp


blood infused diamond (unactive) => blood infused diamond (active)
tier4 120000lp


blood infused diamond (active) => bound diamond
tier5 10000lp


Don't think it should be compared to the cost of binding ritual, looks terrible

**Pull request merged**
