### PR TITLE
Update CuttingaTreelogb-AAAAAAAAAAAAAAAAAAAC5w==.json

### PR DESCRIPTION
**Pull request by Eldrinn-Elantey**

### CODE REVIEW

**Comment by chochem** [comment]
if it doesn't work, then it should be fixed and not just the text changed to 'should'.

**Comment by Eldrinn-Elantey** [comment]
I forgot to state the reason for the change. I think it will be logical if in similar quests will be specified equally this point

**Comment by Eldrinn-Elantey** [comment]
Now I made a big axe out of bronze and the quest counted.

**Comment by chochem** [comment]
I am confused by what you are saying, but I guess that means we can close this?

**Comment by Dream-Master** [comment]
yes close it

**Comment by Eldrinn-Elantey** [comment]
I suggested changing the line that the quest will accept a tool made of any material to the same line that is written in the hammer quest

**Pull request closed without merging**
