### PR TITLE
Fix ReinforedGlass Plate

### PR DESCRIPTION
**Pull request by yukieiji**
Infusion recipe does not have Oredict enabled, so I'm specifying a specific item

### CODE REVIEW

**Comment by Prometheus0000** [comment]
Infusion auto-oredicts

**Comment by Prometheus0000** [comment]
Also, from what I remember, making it ore:something causes it to not work. Did you test this ingame? Also, what problem are you trying to solve here?

**Comment by Elisis** [comment]
Are there even any other entries for plateReinforcedGlass? It seems pretty specific...

**Comment by yukieiji** [comment]
This request is a fix for an issue that can't craft of shield blocks because the ore dictionary isn't supported.
Also increase the accuracy of the NEI search by matching the items that are automatically converted.

**Comment by yukieiji** [comment]
Seems to work fine in-game.

**Comment by yukieiji** [comment]
@Elisis This should be the only ones as there were not many recipes that use Reinforced Glass Plate.

**Comment by Prometheus0000** [comment]
Again, _infusion already auto-oredicts_. Did you check if it works already? Because I had no problem making the thaumic restorer. And as far as I know, there's nothing to oredict it _with_. Is there more than 1 reinforced glass plate?

**Comment by yukieiji** [comment]
It looks like there are two plates.

**Comment by Prometheus0000** [comment]
Are you saying that they're not oredicted against each other? Maybe that's on purpose? Are they made of the same thing?

**Comment by yukieiji** [comment]
Recipes such as Unrouted Transport Pipe can be created with both "Reinforced Glass Plate" and "Molten Reinforced Glass Plate".
However, MT script recipes such as Wand Focus:Shield can only be created with "Reinforced Glass Plate" (NEI search has to be done with it). and "Reinforced Glass Plate" is converted to "Molten Reinforced Glass Plate".

**Comment by Prometheus0000** [comment]
Someone has done something to mess with the reinforced glass plate that you normally make/use. The GT one did not exist before AFAIK.

**Comment by Prometheus0000** [comment]
I guess it's because of https://github.com/GTNewHorizons/GT5-Unofficial/commit/9f8a8ac1bdcc360d3efd38670f20bbba6b8a28ca#diff-faf76538da89119ddb2b992386b619fd4152e300dd5cf01989b79d036d13690f somehow?

**Comment by Prometheus0000** [comment]
It seems something other than GT or the coremod is doing this, but I'm not sure what. Using a stripped instance from 2.1.0.7 shows only 1 plate, even if I update those mods.

**Comment by Prometheus0000** [comment]
OK, I have no idea where this is coming from. It's still there if I disable the line in the hot ingot commit, it disappears if I remove the material (but doesn't crash and tell me where it's creating the plate), it doesn't appear to be being created because of the config file (updating them all changed nothing). But in my stripped instance, it doesn't exist.

**Comment by Dream-Master** [comment]
@Glease any idea ?

**Comment by Glease** [comment]
That's just hot ingot. It had nothing to do with normal plates.

**Comment by Dream-Master** [comment]
@yukieiji @Prometheus0000 @Glease @Elisis is this fix working or we need another solution ?

**Comment by Prometheus0000** [comment]
It would be nice to find where this thing is coming from, but until someone does, the recipes need fixing since it unifies to the new one, you can no longer craft the old one, but none of the recipes (at least the ones here) accept the new plate. Yukieiji said it works, so...

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
