### PR TITLE
Add another IV-circuits for Thaumium Drill

### PR DESCRIPTION
**Pull request by MotiasF33**
maybe better avoid using things like circuits in the infusion?

### CODE REVIEW

**Comment by Prometheus0000** [comment]
This is about oredicting circuits, right? Please look at #6474. This pr is completely useless. And remember to use search next time.

**Review by GTNH-Afx237v7 — CHANGES_REQUESTED** [review]
I can take a look at this item however it is highly likely that this won’t work - detailing the ingredients borks because of different IDs. See also #6562.

**Comment by Dream-Master** [comment]
yea something's wrong. I close this now. Feel free to make a new pr

**Comment by GTNH-Afx237v7** [comment]
As I just learned it seems that Minetweaker does not accept oredict for infusion recipes...

**Pull request closed without merging**
