### PR TITLE
Remove plasma cell spam

### PR DESCRIPTION
**Pull request by GTNH-Colen**
Screenshot 2022-01-29 at 21 18 24
Bye bye useless items.

### CODE REVIEW

**Comment by Dream-Master** [comment]
not lets add more entry to scripts. Why we not using inpure on this items as well ?

**Comment by GTNH-Colen** [comment]
> not lets add more entry to scripts. Why we not using inpure on this items as well ?

Because this item is totally useless, it's an unfinished feature from like 6 years ago that shouldn't even be here.

**Comment by Dream-Master** [comment]
sure but lets use inpure core for hide items in the future. I want that we add all nei hide recipes there.

**Comment by Dream-Master** [comment]
i am not against the hiding of this cells

**Pull request closed without merging**
