### PR TITLE
remove grapehen and Platinum

### PR DESCRIPTION
**Pull request by Dream-Master**
We need to make MT more usefull but not for skipping process lines https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9126#issuecomment-995169576

### CODE REVIEW

**Comment by boubou19** [comment]
I thought the idea was to add energy sinks for players who want to pay energy for those without having to set things up? Also, you nerfed the graphene MT recipe to use x4 more power 5 days ago https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/ca8d06b6003f7e33c825314514d27dc8136612a0 I don't understand this one

**Comment by Sphyix** [comment]
Partially skipping lines can be useful endgame aswell.
I'm still of the idea that the whole platline should be skippable at least at UEV, as it is too slow for the amount of stuff that is needed in some crafts, and if made faster it can lag the server.

**Comment by draknyte1** [comment]
You can probably mill half the plat line

**Comment by Dream-Master** [comment]
we can maybe add the MT recipe to uv or zpm and enable all the shit back

**Comment by Dream-Master** [comment]
> You can probably mill half the plat line

Dont worry i have an eye on it and will balancing everything :)

**Comment by draknyte1** [comment]
> > You can probably mill half the plat line
> 
> Dont worry i have an eye on it and will balancing everything :)

For the cost of it, people later game should have the option to skip the processing chain. Look at aluminium, titanium and tungsten. They already allow this.

**Comment by Sphyix** [comment]
> we can maybe add the MT recipe to uv or zpm and enable all the shit back

If there is a way to tier the recipes in the molecular transformer, that's a good idea to make some lines skippable at high tiers.
Other alternative would be to just approve this thing and add pure ores of the materials that should be skippable to deep dark

**Comment by Dream-Master** [comment]
> > > You can probably mill half the plat line
> > 
> > 
> > Dont worry i have an eye on it and will balancing everything :)
> 
> For the cost of it, people later game should have the option to skip the processing chain. Look at aluminium, titanium and tungsten. They already allow this.

yes because no one was checked balanced since yet :)

**Comment by Dream-Master** [comment]
> > we can maybe add the MT recipe to uv or zpm and enable all the shit back
> 
> If there is a way to tier the recipes in the molecular transformer, that's a good idea to make some lines skippable at high tiers. Other alternative would be to just approve this thing and add pure ores of the materials that should be skippable to deep dark

Make a new rfc issue for a MT rework

**Comment by draknyte1** [comment]
> > > > You can probably mill half the plat line
> > > 
> > > 
> > > Dont worry i have an eye on it and will balancing everything :)
> > 
> > 
> > For the cost of it, people later game should have the option to skip the processing chain. Look at aluminium, titanium and tungsten. They already allow this.
> 
> yes because no one was checked balanced since yet :)

Then remove ore with pure aluminium, pure titanium, pure tungsten, etc.

**Comment by Dream-Master** [comment]
> > > > > You can probably mill half the plat line
> > > > 
> > > > 
> > > > Dont worry i have an eye on it and will balancing everything :)
> > > 
> > > 
> > > For the cost of it, people later game should have the option to skip the processing chain. Look at aluminium, titanium and tungsten. They already allow this.
> > 
> > 
> > yes because no one was checked balanced since yet :)
> 
> Then remove ore with pure aluminium, pure titanium, pure tungsten, etc.

Would be an honor to do that. But i think i get killed instant :P

**Comment by Elisis** [comment]
As long as the assembler graphene recipe is made more sane I'd personally be fine with this. Do we have anymore higher tier players who want to comment though?

**Comment by Dream-Master** [comment]
not sure if we can output more than one thing out of an assembler?

**Comment by Pxx500** [comment]
imo neither of the recipes should be removed, maybe molecular transformers' crafting recipe should be changed to ZPM/UV+ so people can't use it early on to skip lines and only later after making them. This would need quite a few recipe changes though since molecular transformer has uses on lower tiers

**Comment by Florexiz** [comment]
I cant see an issue with skipping platinum more effectively. You can do this with ebf anyway, MT just give you another option to dump energy for Pt, you still don't recieve any byprodts required at iv
Same with graphene. You save what? Silicon? Just leave it as second option, it even makes more sense than using clay and chip wafers lol

**Comment by Pxx500** [comment]
> I cant see an issue with skipping platinum more effectively. You can do this with ebf anyway, MT just give you another option to dump energy for Pt, you still don't recieve any byprodts required at iv Same with graphene. You save what? Silicon? Just leave it as second option, it even makes more sense than using clay and chip wafers lol

well the thing is that the line is supposed to be the best method of production, ebf is much simpler but the efficiency is much lower making it balanced, but balancing pure energy is hard and later you can get the item cheaper with molecular transformer than with the production line (molecular is technically still more expensive but you don't care about enegry at this point)

**Comment by bombcar** [comment]
Perhaps a new GT machine MT should be added where we can control the required voltage of recipes, and slowly migrate everything over to that. As it is the MT will work on LV, just very slowly n

**Comment by Dream-Master** [comment]
let wait for the multiblock and remove MT itself

**Pull request closed without merging**
