### PR TITLE
2.7 Endgame quests

### PR DESCRIPTION
**Pull request by serenibyss**
- Moves the HIP compressor out of Mass Processing to the ZPM page, since it is now mandatory ZPM progression
- UIV changes:
  - Rearranges the tab to fit new quests
  - Moves Fusion MK5 quest from UMV to UIV
  - Adds a link to Crafting Input Buffer quest to the Spacetime quest
  - Moves wireless energy hatch quest from UMV to UIV, change icon to UEV wireless hatch since this is the farthest craftable at this point
  - Mention in Pico circuit quest that it is not long for this world (new circuit line to replace it slated for 2.8)
  - ADD: Crayon and Melon (Creon and Mellion)
  - ADD: No, it's not a Typo (Phonon Transfer Medium)
  - ADD: Star Fuel and Dark Matter
  - ADD: Pseudostable Black Hole Containment Field (written by @FourIsTheNumber)
  - ADD: Project Godforge
  - ADD: An Even More Mega EBF (Helioflare Power Forge)
  - ADD: Helioflux Melting Core my Beloved
  - ADD: Heliothermal Plasma Fabricator
  - ADD: Heliofusion Exoticizer
- UMV changes:
  - Rearranges the tab to fit new quests (and because I didn't like the arrangement at all)
  - Move T3 Space Pump from Endgame Goals to UMV
  - ADD: Wireless Multi-Amp Hatches
  - ADD: Tier 4 QFT Catalysts
  - ADD: A Second Ring has Hit the Godforge (Godforge second ring)
  - ADD: Raw Stellar Plasma
  - ADD: What Do I Use This Stuff On? (info quest mentioning to save white dwarf matter, since it has no uses other than tiered EOH blocks and uses with later EOH materials)
  - ADD: Magnetic Monopole Matter (Magmatter)
- Endgame Goals changes:
  - ADD: Rule of Threes (Godforge third ring)

Quests for follow-up PRs: Antimatter, Legacy Stargate of Harmonic Breakthrough

### CODE REVIEW

**Comment by serenibyss** [comment]
UIV:
image

UMV:
image

**Comment by serenibyss** [comment]
Note for the UIV page: there is a line from UIV energy hatch -> Pico circuit that is not ideal, but this link will be removed in 2.8 when exotic circuits are added, since exotic circuits will replace pico circuit, and will be gated on Heliofusion Exoticizer (the quest directly above Pico circuits in the current layout)

**Review by FourIsTheNumber — APPROVED** [review]

**Comment by chochem** [comment]
image

this looks pretty messy

**Comment by serenibyss** [comment]
> this looks pretty messy

See my comment, 

> Note for the UIV page: there is a line from UIV energy hatch -> Pico circuit that is not ideal, but this link will be removed in 2.8 when exotic circuits are added, since exotic circuits will replace pico circuit, and will be gated on Heliofusion Exoticizer (the quest directly above Pico circuits in the current layout)

I realize its messy but the rest of the page flows very well, and this quest link will disappear soon so I think it's acceptable

**Comment by chochem** [comment]
if you want it to disappear then just hide it. otherwise just putting the two smaller quests below takes like 2 seconds.

**Comment by chochem** [comment]
on a similar note, why are you hiding the deps between these 4 quests?

image

there is nothing in the way.

(unrelated but is the texture wip or are they all meant to look the same?)

**Pull request merged**
