### PR TITLE
Thaumcraft quest tab overhaul

### PR DESCRIPTION
**Pull request by chochem**
Draft of a full Thaumcraft quest tab overhaul, authored by AcaMetis. (also thanks to notapengiun for the help in transfering it here)

This is not finished. Besides some checking of contents and progression, known issues are

- [ ] some quests are deleted that maybe shouldnt be. (Or maybe they should be, but then we should be clear about it)
- [ ] some quests were deleted and remade which changes their quest id and thus removes progress from players. This should be fixed. (e.g., the scepter quest. no full list right now)

### CODE REVIEW

**Comment by Dream-Master** [comment]
@chochem @NotAPenguin0 any news about this ?

**Comment by chochem** [comment]
will start on redoing it soonish. might wait for after 2.6.1 and that dcysteine pr though

**Comment by Dream-Master** [comment]
> will start on redoing it soonish. might wait for after 2.6.1 and that dcysteine pr though

@D-Cysteine wait for you with the quest format change .

**Comment by chochem** [comment]
yea I just wrote them to go ahead.

**Pull request closed without merging**
