### PR TITLE
Fix NEI search for fluids or dusts

### PR DESCRIPTION
**Pull request by chochem**
dont collapse all the fluids or all the dusts. Those are among the most important things to search for in NEI.

### CODE REVIEW

**Comment by Caedis** [comment]
Dusts and cells are also some of the largest groups

**Comment by Caedis** [comment]
Search iron dust, get a group of only iron dusts
image

Search molten iron, get group of only molten irons
image

Search ironwood dust, only get ironwood dust
image

**Comment by Ruling-0** [comment]
Having played with this for a few days now, I pretty much have to always re-open these two groups on startup because most dusts/fluids you search for are part of groups. The feature is still nice because there are _loads_ of other groups that it does hide, making it easier to find the aforementioned dusts/fluids.

As I understand, the PR is just preventing dust/fluids from being auto-collapsed but still grouped, which means I can collapse the groups if needed, but it saves the couple clicks every time the game is launched within the first few recipe searches.

**Comment by Caedis** [comment]
@slprime thoughts on a something that would allow a certain group to be expanded by default?

**Comment by slprime** [comment]
> thoughts on something that would allow a certain group to be expanded by default?

I can save the collapsible groups state per player

**Comment by Caedis** [comment]
Something that I do notice when opening NEI for the first time is the page count will be in the hundreds, but after a couple seconds it will drop down to 31 (full pack)

**Comment by slprime** [comment]
Сollapsible items apply after all NEI addons. and generate more 600 filters also takes time.
I tried to speed up the groups as much as possible, but that's all I could do.

**Comment by Caedis** [comment]
Ahh, good to know.
Would it be possible to add a way to mark a group in the config file as expanded by default?

**Comment by slprime** [comment]
ok i will do it

**Comment by chochem** [comment]
> Search iron dust, get a group of only iron dusts image
> 
> Search molten iron, get group of only molten irons image
> 
> Search ironwood dust, only get ironwood dust image

try searching for any chemical stuff and you will understand the problem. like lets say 'sulf'.

we cant group dusts of completely different materials or cells of completely different materials. They have absolutely nothing to do with each other.

**Comment by slprime** [comment]
I think you don't quite understand the meaning of groups

**Comment by chochem** [comment]
yes I am well aware you can open them lol XD
I understand perfectly, I have this on nightly.

if you actually play GTNH you should know that there is no reason to group these. they dont belong together in any meaningful way. players (and devs) search for materials constantly, having to open shit each time is very frustrating.

**Comment by slprime** [comment]
why need open it every time? do you play the game or do you constantly reload it?

**Comment by Ya9yu** [comment]
image
Previously, you had to search among all the items containing sulf in the name for what you needed.
image
Now you can simply select a collapsed group of items that you need and search among these items
image
It looks much more clear among the items with iron in the name, now you can just select the collapsed group that you need, and not search among dozens of different items

I don't see any problem with this at all, for people who are annoyed by constantly closing groups, you can add a setting that leaves them open, for developers you can simply disable hiding groups 
(Especially if you haven't left the world, the group you opened will remain open)

**Comment by theMegaTech** [comment]
Iron and steel are some great examples, yeah. It's not incorrect that you still need more clicks, but when i search for, let's say, iron 3 chloride, i know i'm searching for a liquid / a cell, so i can just go iron -> click cells group -> locate it easily, instead of navigating bajillion of random types of items GT (and other mods, for common materials like iron/steels/copper) adds. So, generally, even if you need a bit more clicks per hour, you save that time by locating things you need way faster. Also, please don't forget that there are newbies that can and will be easily overwhelmed by material spam in nei and groups do help them by narrowing down the search by a lot.

_Also, a bit of an unasked opinion, but i think deleting a whole group by default because of your personal dislike of it and calling it "a fix" is not really professional._

**Comment by chochem** [comment]
@theMegaTech this was after discussion on discord and is about something that is not in any stable yet, please dont insult people based on stuff you know nothing about. That is not cool.

**Comment by chochem** [comment]
To get back to the topic, saving states certainly helps a lot in general and would be a good change.

These particular groupings still dont make much sense I would say.
Imo, a good use of this feature is to group together and thus hide away spammy niche items that are all very similar. These two groups are the opposite. These are high importance items that are regularly searched for and dont really have anything to do with each other.

**Comment by slprime** [comment]
I do not agree with the deletion of these groups. People wrote here about this groups. Why you ignore other people's opinions?

how do these groups differ from the grouping of bolt,  plates, etc. ?

**Comment by chochem** [comment]
some people agree and some disagree it seems. and one admin doesnt like the feature as whole.

> How do these groups differ from the grouping of bolt, plates, etc. ?

you look for fluids and dusts when you look for materials (which you do a lot).
no fluids (except molten) have plates or bolts and its at best inconsistent for solids, so neither is reliable when looking for materials.

**Comment by Ethryan** [comment]
I like the Dusts and Cells groups, since that means I can close them and keep them out of the way. That way I can open them when I am actively searching for a recipe using them, and keep them out of the way when I'm loopking for something else.

**Comment by slprime** [comment]
It seems to me that your only problem is that the group state is not saved after re-entering the game. and you are trying to solve this in a radical way.

**Comment by chochem** [comment]
ill close it for now. clearly the defaults are not in a good place but I have also no patience to fight about something like this.

**Comment by chochem** [comment]
dream says he wants it or wants it open at least

**Comment by slprime** [comment]
> P.S. I will make saving states for collapsible groups

**Comment by slprime** [comment]
https://github.com/GTNewHorizons/NotEnoughItems/pull/510 This PR preserves collapsibleitems states. this should solve your problem

**Comment by slprime** [comment]
@chochem, my last PR solved your headache with these groups? shouldn't close this PR?

**Comment by Dream-Master** [comment]
Yea we close this when your @slprime pr is merged ? Or was this already merged ?

**Comment by chochem** [comment]
> @chochem, my last PR solved your headache with these groups? shouldn't close this PR?

You should read above. I gave up a while back, this is open because dream wants it open.

**Comment by slprime** [comment]
ok then i'll ask him

**Comment by Dream-Master** [comment]
I just wants it open because idk it was  fixed elsewhere

**Comment by chochem** [comment]
dream no longer wants it open

**Pull request closed without merging**
