### PR TITLE
Disable One Ring

### PR DESCRIPTION
**Pull request by Prometheus0000**
Disables getting One Ring in Dungeon Chests

Because it's super OP, and mitch said it was already supposed to be disabled.

### CODE REVIEW

**Comment by Rakdarian** [comment]
No.

**Comment by Prometheus0000** [comment]
Not disabled enough? Should we remove the item from people inventories and chests too?

Or you could give more of a comment than just 'no'.

**Comment by mitchej123** [comment]
Here's the last discussion on the topic - https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3909

**Comment by Prometheus0000** [comment]
If someone has the time to change it, that's great. But it doesn't seem that way right now, so let's disable it until then.

**Comment by Rakdarian** [comment]
No as in, dont disable it.

**Comment by Prometheus0000** [comment]
_Why?_

**Comment by mitchej123** [comment]
+1 to disabling it.  Broken AF

**Comment by Rakdarian** [comment]
Because its a fan favorite and enables variant ways of play. It also allows more casual players to move passed the early game better through exploration. Additionally it encourages early game exploration in general

**Comment by Prometheus0000** [comment]
It makes you _invincible_. We don't have infernals and special mobs just so you can use the ring to not have to worry about them. GTNH != Casual. It's _supposed_ to be hard.

If you wanna re-code it so it raises your warp 1 every minute, plus other nasty effects, maybe it'd be worth keeping around. Any other nerf to it's functionality would basically be removing the invincibility, making it useless. Or making it a UHV recipe or something.

**Comment by ScriptedPiky** [comment]
Agreed with the disabling until an actual rework is done for the One Ring. Another additional problem with the said item is practically ignore some of the warp effects on public or private servers running plugins, namely, town plugins that prevent mobs from spawning or entering their town, effectively negating a dangerous off-set of the One Ring. With a similar problem being that players can use said *invincibility*, not purely *invisibility*, to go off into life-threating areas without a single worry. Going to Venus or Cent. Bb that kills you instantly regardless of most armor or how much health without having the right suit on? Heck, the One Ring prevents that entirely, apparently. Aside from the dangerous warp increase, especially without abusing town plugins or such, the One Ring is too much of a benefit that should not offer *invinicibility* as a loot-item. It's kinda like applying a severely nerfed part of the Infinity Armor but to a single ring.

**Comment by Dream-Master** [comment]
@Prometheus0000 you need to disable or remove the quest also if the ring not exists.

**Comment by NoX-programer** [comment]
I voting against any nerf of a ring (in this case) including ++warp, but voting for hard recipe for game balance.

**Comment by Prometheus0000** [comment]
? A recipe would be a nerf though.

**Comment by NoX-programer** [comment]
The nerf of recipe is the acceptible, I'm sure. The nerf of functionality is the evil.

**Comment by Rakdarian** [comment]
The core game also shouldnt be changed to cater to servers. If the downsides of one ring are mitigated by the fact that some servers offer overpowered protection thats the fault of the server, not the one ring. And personally servers should be anarchy anyways. You dont make the teleporting options easier because /home and /warp [location] exist and needs to compete, and you dont disable one ring because some servers offer overpowered protection

**Comment by mitchej123** [comment]
One can enable it on their own server if they want it.  The pack has always catered to dream's vision and the official servers.

**Comment by boubou19** [comment]
That's not even a matter of "servers offering overpowered protection". You simply become invincible, so ez bosses, no need to worry about oxygen, etc.

**Comment by Rakdarian** [comment]
Actually if you make the damage from oxygen marked as the same as from the chaos dragon projectiles itll hit through one ring. I should also mention that runic shielding also gives protection agaisnt lack of oxygen on other planets so thats something that should be considered.

I was mainly addressing that if an argument is trying to say that because of how towny works with preventing warp effects from going off then the issue isnt with the ring, its with towny. Now if the warp effects arent enough of a discouragement thats another story. but im mainly concerned with the "Towny makes it overpowered so we should disable the ring" Id rather disable towny tyvm

**Comment by mitchej123** [comment]
The ring makes the ring overpowered.  It's unbalanced & too easy to get, we should remove it.

**Comment by Dream-Master** [comment]
ok i close this now. We change the chest llot and make a recipe

**Comment by Dream-Master** [comment]
vote was clear

**Comment by Dream-Master** [comment]
image

**Pull request closed without merging**
