### PR TITLE
Added TC Aspects for more mobs

### PR DESCRIPTION
**Pull request by dipo33**
This PR includes the following updates:

- Reworked and completed the aspects for mobs from SpecialMobs.
- Added aspects for the Witchery Hellhound.
- Added aspects for mobs from BiomesOPlenty.
- Added aspects for mobs from Ender Zoo.

Related PR for the mod generating these configs: https://github.com/GTNewHorizons/ThaumcraftMobAspects/pull/3

### CODE REVIEW

**Comment by dipo33** [comment]
Hey @GTNewHorizons/developers would anyone be willing to review this?

**Comment by dipo33** [comment]
Also a note here @Alastors  , there is a really few small differences compared to the aspects in the other PR. For few mobs, I have also added some non-vanilla TC aspects like magnet for mobs attracting other mobs, or for example glory aspect for the fallen knight. I didn't add those aspects in the other PR as I didn't want to add another hard dependencies to that mod.

**Comment by Alastors** [comment]
> Also a note here @Alastors  , there is a really few small differences compared to the aspects in the other PR. For few mobs, I have also added some non-vanilla TC aspects like magnet for mobs attracting other mobs, or for example glory aspect for the fallen knight. I didn't add those aspects in the other PR as I didn't want to add another hard dependencies to that mod.

Feel free, you don't have to add them as hard dependencies tho, you can add aspects as part of a soft dependency

**Comment by Alastors** [comment]
If you're gonna do that though, just ping me when you're done

**Comment by dipo33** [comment]
I believe it's enough for those aspects to be here in GTNH so I will leave it as is @Alastors.

**Review by Alastors — APPROVED** [review]

**Pull request merged**
