### PR TITLE
Mirror

### PR DESCRIPTION
**Pull request by Prometheus0000**
They only move essentia around, why are they gated so far? As mentioned in a previous issue 
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3424#issuecomment-540146060

### CODE REVIEW

**Comment by KiloJoel** [comment]
Strongly support this. I had been meaning to suggest this myself

**Comment by KiloJoel** [comment]
I would personally say they would be better a bit earlier even. But any buff is a positive for this.

**Comment by KiloJoel** [comment]
> 
> 
> I would personally say they would be better a bit earlier even. But any buff is a positive for this.

To make a specific suggestion: vibrant alloy instead of titanium

**Comment by Prometheus0000** [comment]
Does anyone _other_ than kilojoel have any comments?

**Comment by repo-alt** [comment]
Can you post a screen of the new recipe? metaitems are, kind of, not very idiomatic

**Comment by Prometheus0000** [comment]
It's just enderium plate to titanium plate, as mentioned in the commit.

**Review by repo-alt — APPROVED** [review]

**Pull request merged**
