### PR TITLE
Quests for new GS multis

### PR DESCRIPTION
**Pull request by glowredman**
The new Planetary Gas Siphon quest is located in the "Space Race" tab:
grafik
grafik

The Space Station quest (`#1067`) has been modified to adapt to the changed space station recipes:
grafik

The Dyson Swarm Ground Unit multi received three new quests, located in the "How to Generate Power" tab:
grafik
grafik
grafik
grafik
grafik
grafik

### CODE REVIEW

**Comment by LewisSaber** [comment]
Can Planetary Gas Siphon Overclock?

**Comment by Dream-Master** [comment]
@glowredman suggestion: make some task optinal like miouzume did for low tier quests. Only the last or the second last task have to retrieval.

**Comment by glowredman** [comment]
> Can Planetary Gas Siphon Overclock?
> 

No, it can't

**Comment by glowredman** [comment]
> @glowredman suggestion: make some task optinal like miouzume did for low tier quests. Only the last or the second last task have to retrieval.

Will do - tommorow

**Comment by Zereff06** [comment]
image
ebergy or energy?

**Comment by glowredman** [comment]
> image ebergy or energy?

energy (fixed now)

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
