### PR TITLE
Adjusting the quest "At the End of..."

### PR DESCRIPTION
**Pull request by Eldrinn-Elantey**
Fixing the required number of frostproof machine casings in the quest since 21 is not enough

### CODE REVIEW

**Comment by boubou19** [comment]
3x3 cube hollow = 26 blocks
26 blocks - controller - energy hatch - maintenance hatch - input bus - output bus =26 - 5 = 21.

**Comment by Eldrinn-Elantey** [comment]
> 3x3 cube hollow = 26 blocks 26 blocks - controller - energy hatch - maintenance hatch - input bus - output bus =26 - 5 = 21.

But what about another one that we spend on the controller? In other quests , this moment takes into account

**Comment by boubou19** [comment]
ah yeah forgot about this one then in this case it's 22.

**Comment by bombcar** [comment]
> ah yeah forgot about this one then in this case it's 22.

Are we consistent on that? Usually I remember building the controller, then building the casings (more) …

**Review by bombcar — APPROVED** [review]
Looks good. If someone overproduced by accident they can save or disassemble

**Pull request merged**
