### PR TITLE
More tgregworks removals

### PR DESCRIPTION
**Pull request by chochem**
cleanup on useless and terrible tinker materials.

### CODE REVIEW

**Review by Dream-Master — APPROVED** [review]
ok from my side

**Comment by boubou19** [comment]
what happens if you already have a tool with this material before config update? does it crash?

**Comment by chochem** [comment]
one second, people are giving me some feedback

**Comment by chochem** [comment]
alright, ready now. combined with the previous pr that is 88 disabled materials.

**Comment by Baerschen** [comment]
> what happens if you already have a tool with this material before config update? does it crash?

Tested it with one of the removed materials and it does not crash. This was the result:
image

**Comment by combusterf** [comment]
Some items that are removed as useless but might not have been intended to be useless:
- `Silicone`, `StyreneButadieneRubber`: Synthetic rubber makes one of the few soft mallets we have in game, and its the best non-magical material for it. Are these affected by this change?
- `Livingwood` and/or `Dreamwood`, would love to see those balanced as better tool handles instead of being unceremoniously removed and give people more reasons to divert into magic.

**Comment by Baerschen** [comment]
>     * `Silicone`, `StyreneButadieneRubber`: Synthetic rubber makes one of the few soft mallets we have in game, and its the best non-magical material for it. Are these affected by this change?
They are not affected

**Comment by combusterf** [comment]
I've added a ticket and plan to pick it up: #17235

**Pull request merged**
