### PR TITLE
Wg transmutation fix

### PR DESCRIPTION
**Pull request by Prometheus0000**
For some completely inexplicable reason, OreDict (or is it material name?) tags that are more than one word don't work unless you put a space in, like 'Infinity Catalyst'. All the ones that didn't work had two 'words', like 'DeepIron' or 'Uranium235'. I have no clue why this fixes it, but it does, so yay. Keep this in mind if anything else is added to the list in the future.

### CODE REVIEW

**Review by Dream-Master — APPROVED** [review]

**Comment by Rakdarian** [comment]
*oh no*

**Comment by Dream-Master** [comment]
oh yes

**Comment by mitchej123** [comment]
How about we balance this instead of just disabling them... :)

**Comment by Prometheus0000** [comment]
This just fixes the _already existing_ blacklist. Deciding what goes on it belongs in an actual ticket.

**Comment by Dream-Master** [comment]
yea for new addition material we can change the amount or so

**Comment by Rakdarian** [comment]
So whats the blacklist now?

**Comment by Prometheus0000** [comment]
The same? Just that it works. I mean seriously, just read what I wrote already.

**Pull request merged**
