### PR TITLE
Dollytooltip

### PR DESCRIPTION
**Pull request by Prometheus0000**
See  #6707

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Prometheus0000 Please add the 3 new tanks too. Not sure if they in 2.0.9.1

**Comment by Prometheus0000** [comment]
Which build would I have to grab off the jenkins to add them to see the size? The coremod?

**Comment by Dream-Master** [comment]
Iron tanks lastest build

**Comment by Dream-Master** [comment]
or check github code/commit or localizer file for name spelling

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
