### PR TITLE
change(GT++)Boiler recipes

### PR DESCRIPTION
**Pull request by Dream-Master**
change the steam Boiler recipes and Chassis
add new Boiler Quests to Mv and Hv Tab

### CODE REVIEW

**Review by Ethryan — APPROVED** [review]
That's a lot of changes to the DQuest file...
You sure @Dream-Master ?

**Comment by Dream-Master** [comment]
@Ethryan there was an id change because some quests are removed so all ids shuffle i guess. Nothing i can do against it. Ingame i looks ok

**Comment by Dream-Master** [comment]
image
image
image
image
image
image
image
image
image
image

**Review by draknyte1 — COMMENTED** [review]
Why make the recipes harder? People don’t make them already as they’re too expensive. 🤦🏻‍♀️

**Pull request merged**
