### PR TITLE
Fix small typo (GNTH -> GTNH)

### PR DESCRIPTION
**Pull request by dirkschut**

### CODE REVIEW

**Comment by bombcar** [comment]
Should this be fixed in the main quest? Not sure why it’s in txloader

**Comment by dirkschut** [comment]
It is where it is because I'm not familiar with this repo and just looked around and found it here. 😄 What location should I fix it instead?

**Review by bombcar — APPROVED** [review]

**Comment by bombcar** [comment]
Yep, that's where it goes!

**Comment by dirkschut** [comment]
> Yep, that's where it goes!

Great. I was just editing in github.dev to just get it done. Didn't want to clone etc. to just fix a simple typo xD

**Pull request merged**
