### PR TITLE
Nuclear Quest Page

### PR DESCRIPTION
**Pull request by Steelux8**
I made a new quest page to cover both nuclear fission and fusion, with more information that isn't generally available anywhere else. I researched the multis to find out some numbers that were not documented, and I explained setups to the best of my ability. I will continue to update these quests as I obtain more information, and as these setups are updated.

### CODE REVIEW

**Comment by glowredman** [comment]
Can you post screenshots of the new quests (if any), which quests are now displayed in the new tab aswell (if any) and which quests are moved (if any)? The diff is too large to be displayed by GitHub.

**Comment by Steelux8** [comment]
> Can you post screenshots of the new quests (if any) and mark which quests are now displayed in the new tab aswell (if any) and which quests are moved (if any)? The diff is too large to be displayed by GitHub.

I myself am shocked as to why the diff is so large. I've made new pages of this size before and this never happened before. I'm gonna try to find out why this happened.

**Comment by glowredman** [comment]
> > Can you post screenshots of the new quests (if any) and mark which quests are now displayed in the new tab aswell (if any) and which quests are moved (if any)? The diff is too large to be displayed by GitHub.
> 
> I myself am shocked as to why the diff is so large. I've made new pages of this size before and this never happened before. I'm gonna try to find out why this happened.

Looks a bit like you didn't have the most recent DefaultQuests.json loaded in MC and acidentally deleted some quests when copying your changes back.

**Comment by Steelux8** [comment]
I used Github Desktop to fetch origin and move over the DefaultQuests file before I started editing. How could I have missed quests this way?

Additionally, how do I screenshot a diff of this size? I haven't figured out what is different other than my new quests.

**Comment by glowredman** [comment]
Alright:
- Did you move any quests? If so, mark them in the screenshot you posted above.
- Did you copy any quests, so that they are displayed in multiple tabs? If so, mark them in the screenshot you posted above.
Everything else is best reviewed by loading the quests and looking at them ingame in my opinion.

**Comment by Steelux8** [comment]
> Alright:
> 
>     * Did you move any quests? If so, mark them in the screenshot you posted above.
> 
>     * Did you copy any quests, so that they are displayed in multiple tabs? If so, mark them in the screenshot you posted above.
> 
> 
> Everything else is best reviewed by loading the quests and looking at them ingame in my opinion.

I moved no quests, nor duplicated any. I thought of doing it, but ended up not reusing any quests.

I have checked the existing quest pages, and everything is exactly the same as before. Even more, I changed to the last merged DefaultQuests file and forced complete some quests after the page I've made, and when switching to my update, they are completed the same way as before. The existing quests seem exactly the same, and the diff is telling me nothing useful, other than that quests might have been switched to a different order in the JSON file, but not in-game.

Was there a change to how these things are generated? There's no way I can tell why the diff is this large.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
