### PR TITLE
ZenScript I18N

### LINKED ISSUE #11671: ZenScript I18N
### Your GTNH Discord Username

MuXiu1997#3167

### Your Pack Version

2.2.3

### Your Proposal

ZenScript files have long been very difficult to localize and automate, so I wish there was a way to make localizing ZenScript files easy

Here is an idea to extract all localizable strings into variables with a specific prefix, so that automation can recognize lines with a specific prefix

```diff
 // --- addTooltip + addShiftTooltip ---
-<Forestry:frameUntreated>.addTooltip("<Hold Shift>");
-<Forestry:frameUntreated>.addShiftTooltip("Durability:"+format.red(" 80"));
-<Forestry:frameUntreated>.addShiftTooltip("Territory:"+format.aqua(" x1"));
-<Forestry:frameUntreated>.addShiftTooltip("Mutation-Rate:"+format.gold(" x1"));
-<Forestry:frameUntreated>.addShiftTooltip("Lifespan:"+format.yellow(" x1"));
-<Forestry:frameUntreated>.addShiftTooltip("Production:"+format.darkGreen(" x2"));
-<Forestry:frameUntreated>.addShiftTooltip("Genetic-Decay:"+format.yellow(" x0.9"));
+var I18N_frameUntreatedTooltip = "<Hold Shift>"
+<Forestry:frameUntreated>.addTooltip(i18n_frameUntreated_tooltip);
+var I18N_frameUntreatedShiftTooltip0 = "Durability:"
+<Forestry:frameUntreated>.addShiftTooltip(i18n_frameUntreated_shiftTooltip_0+format.red(" 80"));
+var I18N_frameUntreatedShiftTooltip1 = "Territory:"
+<Forestry:frameUntreated>.addShiftTooltip(i18n_frameUntreated_shiftTooltip_1+format.aqua(" x1"));
+var I18N_frameUntreatedShiftTooltip2 = "Mutation-Rate:"
+<Forestry:frameUntreated>.addShiftTooltip(i18n_frameUntreated_shiftTooltip_2+format.gold(" x1"));
+var I18N_frameUntreatedShiftTooltip3 = "Lifespan:"
+<Forestry:frameUntreated>.addShiftTooltip(i18n_frameUntreated_shiftTooltip_3+format.yellow(" x1"));
+var I18N_frameUntreatedShiftTooltip4 = "Production:"
+<Forestry:frameUntreated>.addShiftTooltip(i18n_frameUntreated_shiftTooltip_4+format.darkGreen(" x2"));
+var I18N_frameUntreatedShiftTooltip5 = "Genetic-Decay:"
+<Forestry:frameUntreated>.addShiftTooltip(i18n_frameUntreated_shiftTooltip_5+format.yellow(" x0.9"));
 
 // --- game.setLocalization ---
-game.setLocalization("tc.research_name.SHARETOME", "Tome of Knowledge Sharing");
-game.setLocalization("tc.research_text.SHARETOME", "[TT] A Goldfish's Diary");
+var I18N_tcResearchNameSharetome = "Tome of Knowledge Sharing"
+game.setLocalization("tc.research_name.SHARETOME", I18N_tcResearchNameSharetome);
+var I18N_tcResearchTextSharetome = "[TT] A Goldfish's Diary"
+game.setLocalization("tc.research_text.SHARETOME", I18N_tcResearchTextSharetome);
 
 // --- NEI.overrideName ---
-NEI.overrideName(<AdvancedSolarPanel:asp_crafting_items:8>, "Irradiant Reinforced Iridium Plate");
+var I18N_advancedSolarPanelAspCraftingItems8 = "Irradiant Reinforced Iridium Plate"
+NEI.overrideName(<AdvancedSolarPanel:asp_crafting_items:8>, I18N_advancedSolarPanelAspCraftingItems8);
 
 // --- displayName ---
-<Railcraft:upgrade.lapotron>.displayName = "Lapatron Loader Upgrade";
-<Railcraft:part.plate:4>.displayName = "Lead Plate";
+var I18N_railcraftUpgradeLapotron ="Lapatron Loader Upgrade"
+<Railcraft:upgrade.lapotron>.displayName = I18N_railcraftUpgradeLapotron;
+var I18N_railcraftPartPlate4 = "Lead Plate"
+<Railcraft:part.plate:4>.displayName = I18N_railcraftPartPlate4;
```

@Dream-Master @Kiwi233 

### Your Goal

/

### Your Vision

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

### PR DESCRIPTION
**Pull request by iouter**
close #11671

### CODE REVIEW

**Comment by Dream-Master** [comment]
@iouter as I said earlier we want to move away from script. Not sure if it is a good idea to add even more to load.

**Comment by iouter** [comment]
this is just a temporary solution, i don't think more scripts will be added to it now.

(and it's really hard to use)

**Comment by Dream-Master** [comment]
@iouter is this tested ?

**Comment by iouter** [comment]
> @iouter is this tested ?

work fine

**Comment by MuXiu1997** [comment]
It just extracts the string into a variable, and essentially doesn't add any more content that needs to be loaded

This serves as a temporary solution that can be very convenient for our localization automation

It's just that the variables are named incrementally which can be relatively difficult to maintain

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
