### PR TITLE
Nasa workbench textures v1 for 2.0.9.1+

### PR DESCRIPTION
**Pull request by Houstonruss**
first pr go gentle

### CODE REVIEW

**Comment by Prometheus0000** [comment]
Is the pufferfish supposed to be there?

**Comment by Houstonruss** [comment]
Of course

**Review by glowredman — CHANGES_REQUESTED** [review]
I don't think the textures go in `resources/assets/galaxyspace/` but in `resources/galaxyspace`, furthermore I'd suggest putting these textures directly in GalaxySpace.

To the textures itself:
- The main Moon Buggy (not the player inventory, the chest slot and the output slot) slots are offset to the left
- The hotbar slots on the unlock texture are offset to the bottom (only 1 pixel or so, really difficult to see)
- The Moon Buggy and Astro Miner textures are missing areas for the text ("Inventory" and "Astro Miner" / "Moon Buggy")
- The yellow parts on the right side unlock texture look a bit cut-off at the edge
- The unlock texture is missing a text area on the top ("Add New Schematic"). I might need to move the text down a bit though, so I'd adapt it to the text area then

The textures itself look great though 👍

**Comment by Houstonruss** [comment]
image
I can tweak the textures later, because i wanted to add "ghost items" (to show you where to put items in the grid) aswell.
If you research the buggy and miner you will ruin the fancy arrows because they won't be in order anymore!

**Comment by glowredman** [comment]
The textures are now loacted in GalaxySpace (https://github.com/GTNewHorizons/Galaxy-Space-GTNH/commit/9b831e50066389ae881c1c4297380ae772aed41f). Please commit/PR all future changes/additions to that repo (you should have access).

**Pull request closed without merging**
