### PR TITLE
Add new warp effects to config

### PR DESCRIPTION
**Pull request by D-Cysteine**
Updating config to use warp levels suggested in:
 * https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8611#issuecomment-958003423

### CODE REVIEW

**Comment by TheElan** [comment]
Are values in quest already updated? If not I would suggest updating them here too, so it's all enters the pack in one PR

**Comment by D-Cysteine** [comment]
Thanks! I've updated the quest.

**Comment by yukieiji** [comment]
There must have been a sentence in Thaumonomicon that needed to be changed.

**Comment by D-Cysteine** [comment]
Thanks! Updated that too, I think

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
