### PR TITLE
fix autoclave of TC dusts / allow autocrafting of Galacticraft items

### PR DESCRIPTION
**Pull request by GTNH-Afx237v7**
fix molten void autoclave recipe of TC crystal powders only giving air shards instead of their respective shards
Change Arc Lamp and Frequency Module recipes to use GT battery instead of GalactiCraft battery to allow proper autocrafting

### CODE REVIEW

**Review by Dream-Master — APPROVED** [review]

**Comment by Prometheus0000** [comment]
1) There's no point fixing typos in comments, they'll all get removed whenever we move to using the script mod
2) What's up with the glowstone torch thing, didn't I fix it already? Did you accidentally use a 3 month old version of this file or something?

**Comment by GTNH-Afx237v7** [comment]
1) it just annoys me
2) no, I copied over from the main repo literally 2 mins before making the PR - did I do sth wrong?

**Comment by Prometheus0000** [comment]
image
^was adjusted 3 months ago (change liquid to null) and again before that

Honestly I dunno what's up with it, but as long as it works, it's fine.

**Comment by Dream-Master** [comment]
> image
> ^was adjusted 3 months ago (change liquid to null) and again before that
> 
> Honestly I dunno what's up with it, but as long as it works, it's fine.

A control circuits is always a good idea

**Comment by Prometheus0000** [comment]
The thing is that I already edited this recipe, including the circuit, but github thinks it's a new change.

**Pull request merged**
