### PR TITLE
Update TimetoGetSomeSte-AAAAAAAAAAAAAAAAAAAATA==.json

### PR DESCRIPTION
**Pull request by Eldrinn-Elantey**

### CODE REVIEW

**Review by chochem — DISMISSED** [review]
the bricks look wrong.

but more importantly: did you look who set it all to one and spoke with them? just going back and forth without communication is not good.

**Comment by Eldrinn-Elantey** [comment]
We need 36 firebricks for each firebrick we need 6 firebricks (36*6=216). For 216 "firebricks" you need to make its dust by mixing brick dust and clay dust for each kraft you get 2 dusts (216/2=108). So for 216 firebrick you need 108 clat dust and 108 brick dust.

What do you mean by "just going back and forth"?

**Comment by chochem** [comment]
I said bricks, not firebricks.

back and forth means these used to have amounts but were then set to just 1. (pretty sure anyway)

**Comment by Eldrinn-Elantey** [comment]
I do not know who previously set the value for these quest stages to 1. I think it does not make sense. Accurate values in the quest will make it easier for players to calculate early on. If you think that this is unnecessary, you can close

**Comment by HoleFish** [comment]
you have to make extra bricks for the quest when you accidentally turn a few into firebricks in advance

**Comment by chochem** [comment]
I would assume these were set to 1 when they werent optional? that would make the most sense. but I have not checked, you certainly should. If thats the only reason then it would be fine to change.

of course your numbers are not correct right now anyway.

**Comment by Eldrinn-Elantey** [comment]
I changed the number of bricks to 432 in the last commit

**Comment by chochem** [comment]
yea but not the unfired lol

**Comment by Dream-Master** [comment]
Why not set the amounts to the bricks you need in total ? Since the quest part are optimal it will not harm anyone. Every time I make a bbf I need to make the math how much bricks I use to not waste to much stuff or run out of materials .

Sure the amounts need to be correct .

**Comment by Eldrinn-Elantey** [comment]
The number of bricks has been adjusted

**Comment by chochem** [comment]
so you want me to do the work dream? :(
alright Ill have a look as to where this came from

**Comment by chochem** [comment]
here you here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7063

**Comment by Dream-Master** [comment]
what you mean @chochem change the other ingredients as well ?

**Comment by Eldrinn-Elantey** [comment]
So what's the solution?

**Comment by Dream-Master** [comment]
I mean how much clay you need in total etc.

**Comment by Eldrinn-Elantey** [comment]
> I mean how much clay you need in total etc.

A total of 720 clay pieces.

**Review by chochem — DISMISSED** [review]
please dont change numbers to random incorrect values.

**Comment by Eldrinn-Elantey** [comment]
> please dont change numbers to random incorrect values.

Why random? The number is calculated using JEC

**Comment by chochem** [comment]
jec isnt magic. if you dont ask the right question you cant expect the right answer.

**Comment by Eldrinn-Elantey** [comment]
The quest is to make 36 firebricks where 4 will be used to craft the controller and the other 32 for the furnace itself. Where's the mistake?

**Comment by Dream-Master** [comment]
i think it was 1008 or so but more than 720

**Comment by Eldrinn-Elantey** [comment]
Previously, it really was 1008. Initially, I did not touch this value, but changed only those that were equal to 1. Perhaps this value is due to the fact that when crushing with a mortar, 1 small dust comes out and when crushing with a macerator, 2 small clay dust comes out

**Comment by Eldrinn-Elantey** [comment]
If you count through the mortar, you will really need 1008 clay. That's how it was originally, I wasn't going to change these values, I made the changes after this message. https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/16692#issuecomment-2219268226

**Comment by Eldrinn-Elantey** [comment]
Which figure is miscounted?

**Comment by Eldrinn-Elantey** [comment]
> Just change it to 1008

Done

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
