### PR TITLE
Changes Simple Washer quest to use new LV simple washer

### PR DESCRIPTION
**Pull request by querns**
# DO NOT MERGE BEFORE THE GT++ PR BELOW IS MERGED:

https://github.com/GTNewHorizons/GTplusplus/pull/783

Now that ULV simple washers are being deprecated, the quests that reference them need to be adjusted. I changed the LV quest for the ULV simple washer to ask for the new LV simple washer, and cleaned up the quest text a bit. I also removed the ULV transformer quest from the LV quest line. (It still exists in the transformer quest line.)

### CODE REVIEW

**Comment by Dream-Master** [comment]
@querns did you push quest to lv tab?

**Comment by querns** [comment]
I didn't add any new quests; I just edited the existing ULV washer one. Is there something extra I have to do?

**Comment by Dream-Master** [comment]
idk in which tab it was but it need to be at lv now

**Comment by querns** [comment]
It's in the LV tab already.

image

**Comment by Dream-Master** [comment]
ok all fine

**Comment by chochem** [comment]
the ULV transformer quest should be deleted properly. its deprecated and with this change no longer useful.

**Comment by bombcar** [comment]
I'd remove the quest, but the transformer may still be used, there's a weird amount of ULV stuff laying around

**Comment by chochem** [comment]
Colen declared it all deprecated by removing the gens.

I know its not in any tooltip, but thats where we are at.

**Comment by Alastors** [comment]
I’m all for it, ULV never made sense to exist in the first place

**Comment by vovaksenov** [comment]
There are a few thinga that ulv is useful for id argue. Many machines can run well on 8 eu/t and this allows using cheap red alloy wires for them. Solar panels are another thing. Deprecating washers is welcome, but ulv as a whole should remain, including the transformer.

**Comment by Dream-Master** [comment]
They will be removed if you like it or not. Ulv is a dead  tier.

**Comment by Alastors** [comment]
> There are a few things that ulv is useful for, id argue. Many machines can run well on 8 eu/t and this allows using cheap lossless red alloy wires for them. Solar panels are another thing. Deprecating washers and generators is welcome, but ulv as a whole should remain, including the transformer. It would be one thing if it was buggy or whatever, but i never had any problems with this stuff, so i see no reason for removing the whole voltage.

You'll still be able to, ULV didn't cause this, ULV was just this hacky shit Alk did for funsies

**Comment by vovaksenov** [comment]
I am completely fine with removing all gtpp stuff for ULV. I only want to make sure nothing from original gt5 is getting removed. The transformer is gt5 native afaik. Tantalum capacitors and batbuffers as well.

**Comment by Alastors** [comment]
> I am completely fine with removing all gtpp stuff for ULV. I only want to make sure nothing from original gt5 is getting removed. The transformer is gt5 native afaik. Tantalum capacitors and batbuffers as well.

We’re removing it from GT as well man, it’s dead, it never made sense to exist in the first place

**Pull request merged**
