### PR TITLE
Quest Changes 5 Aug

### PR DESCRIPTION
**Pull request by Naptik**
Fixed Typos.

Added a quest for killing the harder version of the gaia guardian in the botania questline.

Added a optional quest for making every botania rune (4 each) in the botania questline.

Changed the Terrasteel quest to show the exact amount of blocks needed to build the Terrasteel multiblock in the botania questline (5 living rocks 4 lapis blocks and the Terrasrtial Agglomrration Plate)

Changed the Alfhiem quest to show the exact amount of blocks needed to build the Alfhiem multiblock in the botania questline (2 natura pylons 3 glimmering woods 1 elven gateway core 8 living woods 2 mana pools)

Changed the 3 Coils quest (infinity hypogen and eternal) coil requirement from 1 to 16 in the multiblock questline because 16 was the requirement in every coil quest so why not make it 16.

Changed the Round one... FIGHT! Quest desc in the botania questline from Summon the gaia boss, then dispatch it to get to the Botania endgame. to Put the 4 pylons down and shift right click the terrasteel ingot on the beacon to summon the Gaia Guardian.

Changed the quest task of the Astro Miner quest in the Space Race questline from 8 Orion Drives to 4 as the astro miner only needs 4. #10960 

Removed the Wooden Armour quest requirement from the Unexpected Bonus quest in the Multiblock Goals questline.

### CODE REVIEW

**Comment by Naptik** [comment]
@Dream-Master

**Comment by Dream-Master** [comment]
Is the creative mana pool already added ?

**Comment by Dream-Master** [comment]
I mean the recipes for it.

**Comment by Naptik** [comment]
> I mean the recipes for it.

yep recipe already added

**Comment by Naptik** [comment]
image

**Comment by Dream-Master** [comment]
Please change the ingot to plate

**Comment by Naptik** [comment]
> Please change the ingot to plate

well that is beyond my knowledge some dev has to do that

**Comment by Naptik** [comment]
@Dream-Master actually i am just gonna remove the creative mana pool quest as i have heard its not the final recipe

**Comment by Naptik** [comment]
@Dream-Master i am just gonna remove the mana pool quest for now just merge this this pr is delaying quest dev

**Comment by Dream-Master** [comment]
Didn’t Combuster add a 9x9 crafting ?

**Comment by Naptik** [comment]
> Didn’t Combuster add a 9x9 crafting ?

its not in the current zeta

**Comment by Dream-Master** [comment]
It was after zeta update yes.

**Comment by Naptik** [comment]
> It was after zeta update yes.

well its not in dev25 so uh now what

**Comment by chochem** [comment]
we can always add the quest for that later.

**Comment by Naptik** [comment]
> we can always add the quest for that later.

yep

**Review by chochem — CHANGES_REQUESTED** [review]
please revert the DTPF quest to ask for only one item each. Quests with that many items are super annoying, even if they technically fit into your inventory (one-by-one).

**Comment by Naptik** [comment]
> please revert the DTPF quest to ask for only one item each. Quests with that many items are super annoying, even if they technically fit into your inventory (one-by-one).

Alright lemme change it

**Review by chochem — APPROVED** [review]
thx :)

**Comment by Naptik** [comment]
oh ok thanks i was changing the top post

**Comment by chochem** [comment]
yea that looks fine too

**Pull request merged**
