### PR TITLE
change default position of waila hud and remove background

### PR DESCRIPTION
**Pull request by Alexdoru**
The goal is to make the game look nicer and more appealing, I changed the default position to be centered at the top but below the boss bar and removed the background because it takes too much space on the screen

### CODE REVIEW

**Review by glowredman — COMMENTED** [review]
If it uses "too much space" why did increase the scale? I personally prefer bottom-right so all in all I don't support this change.

**Comment by glowredman** [comment]
That doesn't answer my question in any way.

**Comment by Alexdoru** [comment]
> That doesn't answer my question in any way.

using values different than 1 makes the text "compressed" it looks very bad 
image

here in scale 1 : 
image

**Comment by Zereff06** [comment]
this is a bad idea by default, but you can add this to the config and anyone can use it at will

**Comment by glowredman** [comment]
With this change, something like this will block the main part of the screen (where the crosshair is). I find this problematic.

**Comment by Alexdoru** [comment]
> With this change, something like this will block the main part of the screen (where the crosshair is). I find this problematic.

do you spend your whole gameplay time looking at ender io conduits filled with 40 different fluids...

**Comment by Alexdoru** [comment]
> uses "too much space" why did increase the scale? I personally prefer bottom-right so all in all I don't support this change.

I increased the scale so we can read better but by removing the background we can now see through and it frees lots of space on the screen to see the actual gameplay

**Comment by POPlol333** [comment]
It's my personal opinion, and it only involve me but I feel like even if it is transparent it's too big, kinda like a visual magnet

**Comment by embeddedt** [comment]
IMHO the background should not be removed. It significantly reduces the contrast of the WAILA information which is unfriendly to new players. I'd say it's better to leave the default and players can customize it to their own personal preference.

**Review by leagris — CHANGES_REQUESTED** [review]
Change rejected

Everyone taste is different. No reason to change the default. Anyone can change these settings to fit needs if it differs from default.
Users are satisfied with current default by a good margin.

**Comment by Alexdoru** [comment]
good

**Pull request closed without merging**
