### PR TITLE
Add quests for Pyrotheum, Lapotron and Energy Bees

### PR DESCRIPTION
**Pull request by Baerschen**
This PR adds quest for bees that are widely used and deserve having quests, namely the Pyrotheum, Lapotron and Energium Bees (aswell as Furious and Volcanic because they are part of the breeding chain).

Below are some pictures of the quest tab and the new quests (blue outline for new quests):

image
They of course have proper requirements but lines that would cross into ther lines are set to be shown only when hovering over the quest.

image
image
image
image
image

### CODE REVIEW

**Comment by chochem** [comment]
why did you put them in the 'main progression'? I dont think that makes sense

**Comment by Baerschen** [comment]
Ah didnt know that was the space for main progression. Can use them of course just put them there because of the fiendish bee conncection

**Comment by chochem** [comment]
thats what the left side of the tab is about yea.

**Comment by Baerschen** [comment]
image
Could do it like this: move the fluix quest to the right to be aligned with the others and move the breeding chain into the empty blue sqaure. Thats a task for tomorrow though as I am rly tired. Will draft this until thats done

**Comment by chochem** [comment]
sounds good to me

**Comment by Baerschen** [comment]
image

Changed as discussed. This PR also adds one requirement to the Lapis quest as that was missing and made the line not seen until hovered over.

**Review by chochem — APPROVED** [review]
nice

**Pull request merged**
