### PR TITLE
Nat gas removal

### PR DESCRIPTION
**Pull request by 0lafe**
Removes Nat gas spawns in the OW. Kind of OP having a decent fuel that's pumpable 1 step before generation, due to rig rates.

### CODE REVIEW

**Comment by Dream-Master** [comment]
Sure but why we don't move it to another planet or moon @0lafe ?

**Comment by quedral** [comment]
why don't you adjust burn value instead of removing? If you have oil somewhere you will have natural gas.   If you remove natural gas then you have remove oil as well.

Again this is one of the stupidest suggestions that i've seen in months. Put this on discord vote and see what you get.

**Comment by Prometheus0000** [comment]
To make it truly useful, you need to turn it into refinery gas, right? Maybe adjust those values to be more expensive?

**Comment by Dream-Master** [comment]
no as the name said refinery gas need some processing. I am against it. But I am also against it remove natural gas complete. @Prometheus0000

**Comment by Prometheus0000** [comment]
My understanding is that you pump Natural Gas (which has a burn value of 20,000 EU), and it's only use is burning or turning it into Refinery Gas (which has a burn value of 160,000 EU). You can use it for other stuff like HOG or cracking, but Refinery Gas' primary use is burning it as fuel as well. I'm saying maybe if the process of turning it from NG to RG was more expensive, it might be more balanced.

**Comment by Extremity4** [comment]
I’m not too sure about the implementation, but I agree with the concept behind this nerf at least. Ideally, refinery gas should be inferior to nitro boosted diesel, benzene, or other more complex refined fuels due to how much simpler it is to produce. In practice, however, refinery gas is so incredibly easy to make and available in such massive quantities that anybody in their right mind can see that it makes more sense to use it over literally any other burnable fuel in MV-IV.
In my own experience in a SSP world, using natural gas allowed me to produce THOUSANDS of eu/t while in MV TIER, with nothing more than an lv chemical reactor and a few lv electrolyzers! It was so powerful that this tiny little setup carried me all the way to naquadah generators in IV. I set up a benzene line in HV and a cetane boosted biodiesel line later in IV just for the fun of it, but despite the higher level of complexity (vastly higher in the case of cetane) and more expensive machines these lines required they ended up being inferior to the MV natural gas setup!
I don’t know whether removing natural gas generation outright from the OW is the best way to go about dealing with it (perhaps gas fields can just be made much smaller?), but it seems clear to me that something needs adjusting here.

**Comment by Dream-Master** [comment]
ok i close this now and open up a new one with addition an cahnges suggested in RFC issue
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5974

**Pull request closed without merging**
