### PR TITLE
Adds quests for the Sunnarium bee (and by extension Glowstone and Gold)

### PR DESCRIPTION
**Pull request by Baerschen**
This PR adds 3 quests and renames 2 to keep Glowstone quests seperate. This completes one task from the monthly ticket (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17882#issue-2640317613)

image
image
image
image

### CODE REVIEW

**Comment by LazyFleshWasTaken** [comment]
> Not only does this bee produce more Glowstone than its parent species, but it's also capable of producing sunnarium. However, this comes at a cost: to breed this bee, you need to provide a superconducting coil.

Could you remove 'to provide'? to provide could mean the coil is consumed and confuse readers.

**Comment by Baerschen** [comment]
> 
> Could you remove 'to provide'? to provide could mean the coil is consumed and confuse readers.

Will do and force push (need to reopen the game though gimme a sec)

**Comment by Baerschen** [comment]
"Not only does this bee produce more Glowstone than its parent species, but it's also capable of producing Sunnarium. However, this requires some technical progress: to breed this bee, you will need to place a Superconducting Coil Block beneath it." Should be fine right?

**Comment by LazyFleshWasTaken** [comment]
> "Not only does this bee produce more Glowstone than its parent species, but it's also capable of producing Sunnarium. However, this requires some technical progress: to breed this bee, you will need to place a Superconducting Coil Block beneath it." Should be fine right?

Sounds good!

**Review by chochem — APPROVED** [review]
looks good

**Pull request merged**
