### PR TITLE
Mainframes, Your First IV Circuit

### PR DESCRIPTION
**Pull request by Eldrinn-Elantey**

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Eldrinn-Elantey what you add to the quest? a bit more info would be nice

**Comment by chochem** [comment]
apparantly it adds 24 smd capacitors. 

The why is not clear though. This is not the fix this quest needed. There actually is outdated info in the description but this does not fix that, actually it makes it worse.

**Comment by chochem** [comment]
I am not just closing though, I will make a better version. + maybe some other fixes

**Comment by Eldrinn-Elantey** [comment]
> I am not just closing though, I will make a better version. + maybe some other fixes

Thanks

**Pull request closed without merging**
