### PR TITLE
Fix issue 6320, no recipe for gooseberry yogurt.

### PR DESCRIPTION
**Pull request by shawnbyday**
Fix issue where gooseberry and yogurt made pineapple yogurt. Issue #6320 

image

image

### CODE REVIEW

**Comment by Dream-Master** [comment]
thanks for add it but we forked Harvestcraft and we can edit it in code. Repo is private. @shawnbyday are you want to be added ?

**Review by Dream-Master — APPROVED** [review]

**Comment by shawnbyday** [comment]
@Dream-Master sure you can add me. I can get it in the code I think.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/harvestcraft @shawnbyday

**Comment by shawnbyday** [comment]
@Dream-Master I made change in code if you prefer that way you can revert the MT script commit.

**Pull request merged**
