### PR TITLE
update DefaultQuests.json with support for IMPLICIT, etc

### PR DESCRIPTION
**Pull request by bombcar**
this uses the new feature, but this changes everything and so this PR is just the new file, no quest changes.

### CODE REVIEW

**Comment by bombcar** [comment]
This is huge but is just because of GTNewHorizons/BetterQuesting/pull/44

**Comment by Glease** [comment]
This could well be a review comment on my earlier PR...

**Comment by bombcar** [comment]
Hold these PR - I may be able to simplify this in the morning

**Comment by bombcar** [comment]
Now clean and nice

**Pull request closed without merging**
