### PR TITLE
Ec2

### PR DESCRIPTION
**Pull request by Dream-Master**
Add back ec2 fluid support since a few fixes by @kubasz was added (only for zeta tesing)

### CODE REVIEW

**Review by GTNH-Colen — CHANGES_REQUESTED** [review]
I don't think this is a good idea, even with a few bugs fixed there are so many still left and not to mention the horrific performance issues of the mod. Best left disabled.

**Comment by Dream-Master** [comment]
@GTNH-Colen make a List which stuff is broken so I can ask @kubasz to try fix it.

**Comment by GTNH-Colen** [comment]
Excessive lag, not just from fluid level emitters but you can see it here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7834

Bad handling of fluids > 2MB https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7699
Dupe: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6330
Another dupe: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5915

Some have been censored because obviously we do not want dupes in public. Everything provided by the mod is done by others, with better performance and scalability. I just do not see the advantage of enabling it again when people will inevitably just bitch more.

**Comment by kubasz** [comment]
@GTNH-Colen 
> Excessive lag, not just from fluid level emitters but you can see it here #7834. Multiple censored dupe bugs, see private repos and everything provided by the mod is done by others, with better performance and scalability. I just do not see the advantage of enabling it again when people will inevitably just bitch more.

The fluid emitter lag was particularly bad as it sent a chunk update every time a fluid amount changed, this is now fixed to only send an update when the amount change triggers a redstone signal strength change just like the ae2 item level emitters. The import/export buses never set their tickrate to IDLE, this is now also fixed and they should behave exactly like ae2 item buses. I did a few tweaks to the fluid storage bus, but it has to trigger updates on its attached block just like the item storage bus, so that's probably not going to get better. Most dupe bugs were related to using the wrong cell api, I have switched it over to the proper one and tested it extensively with large GT cells and now xu2 drums, and couldn't find any way to dupe or void liquids so far. I think it can be a nice alternative to eio ender fluid conduit networks, with a terminal to view/access fluids, and storage monitors to display levels anywhere in a factory - both of which are not replicated by other mods afaik.

As for general performance, I removed some particularly bad code that was causing lots of allocations, other than that a savefile or instructions for a specific known-laggy setup would be necessary to profile the game and pinpoint what part of the code is causing issues, and I'd be happy to fix them if possible. (or even just a opis/visualvm profiled stacktrace could work)

**Comment by Chaoschaot232** [comment]
@kubasz - I like how you fixed a lot of EC2 stuff :3 - I can't wait to play with my ME later on with all these fixes :)

Maybe the player mentioned in #7834 can also test what you have changed as they have reported it. Getting feedback from them with there network could be a good reference ;)

**Comment by kubasz** [comment]
@GTNH-Colen Any chance of revisiting your opinion after the changes in <https://github.com/GTNewHorizons/ExtraCells2/pull/55>, <https://github.com/GTNewHorizons/ExtraCells2/pull/54>, <https://github.com/GTNewHorizons/ExtraCells2/pull/53>, <https://github.com/GTNewHorizons/ExtraCells2/pull/52>? If any more bugs or laggy code is found after all these changes, they can be fixed, and the only realistic way to do that is having players test EC2 in the dev pack.

**Review by Connor-Colenso — APPROVED** [review]
Worth a shot.

**Comment by joshaup1999** [comment]
Is this in the zeta test pack atm?

**Pull request merged**
