### PR TITLE
Add script QS recipe

### PR DESCRIPTION
**Pull request by Prometheus0000**
See #7455 for why.

### CODE REVIEW

**Comment by Dream-Master** [comment]
Does it fix the problem or not ?

**Comment by GTNH-Afx237v7** [comment]
Yes it does. Adding it to the script file works fine, I tested it with 2.1.0.0.

**Comment by Dream-Master** [comment]
but if you use it for charcoal woks it too?

**Review by Dream-Master — APPROVED** [review]

**Comment by GTNH-Afx237v7** [comment]
Yes, just tested and it works fine, too

**Pull request merged**
