### PR TITLE
Adjust quantum chestplate quest

### PR DESCRIPTION
**Pull request by Pxx500**
image

New text, everything tested in game  (2.4.0RC1)

### CODE REVIEW

**Comment by Pxx500** [comment]
resolves 
image
in monthly ticket for quest changes @chochem

**Comment by Pxx500** [comment]
> hmm. so you dropped all mention of speed? I guess that works, its too much of a hot topic for some devs that its hard to even talk about it normally.

I tested them all, they have the same speed

**Comment by Pxx500** [comment]
> However it also has another bug currently that completely drove me mad when I tried it #14318 I went back to nano and still wouldnt recommend this one to anybody despite that hodgepodge buff.

I'd just ignore that, more funny than annoying. Not gamebreaking or anything

**Comment by chochem** [comment]
maybe just me then, I found it very annoying.

**Review by chochem — APPROVED** [review]

**Pull request merged**
