### PR TITLE
Disable pollution until it's reworked

### PR DESCRIPTION
**Pull request by mitchej123**

### CODE REVIEW

**Review by botn365 — APPROVED** [review]

**Review by Prometheus0000 — APPROVED** [review]

**Review by Elisis — APPROVED** [review]

**Review by basdxz — APPROVED** [review]

**Comment by basdxz** [comment]
does papi dream approve?

**Review by GTNH-Colen — APPROVED** [review]

**Review by MatthewCOwen — APPROVED** [review]

**Review by glowredman — APPROVED** [review]

**Review by ScriptedPiky — APPROVED** [review]

**Review by Ethryan — APPROVED** [review]

**Review by leagris — APPROVED** [review]

**Review by gordominossi — APPROVED** [review]

**Comment by Dream-Master** [comment]
ok I approve it under the following agreement: Now we disable it in 2.1.1.0 but until 2.1.2.0 I want a new working version of pollution or I re enable it. This is not negotiable.

**Review by boubou19 — APPROVED** [review]

**Comment by leagris** [comment]
> ok I approve it under the following agreement: Now we disable it in 2.1.1.0 but until 2.1.2.0 I want a new working version of pollution or I re enable it. This is not negotiable.

There were really involved attempts into defining the **working pollution** in Discord's `#pollution-rework`, but so far despite the crying calls to define pollution and give it goals, it has endlessly ran in circles with a multiplicity of suggested effects of pollution, without any basis or purpose.

Pollution is a solution to which we are still looking for the problem it should solve.

Would you please elaborate on what should be a **working pollution** to be implemented as a 2.1.2.0 deadline?

**Comment by Glease** [comment]
In other words, maybe finally decide which of the [ideas](https://gtnh.miraheze.org/wiki/Pollution_revamp) and/or [visions](https://gtnh.miraheze.org/wiki/Pollution_revamp_visions) is suitable for pack.

**Comment by iouter** [comment]
I suggest open an issue for regularly summarize the goals and plans.

**Comment by Dream-Master** [comment]
@mitchej123 if i got your word under my comment now i merge it.

**Comment by mitchej123** [comment]
> @mitchej123 if i got your word under my comment now i merge it.

I'll commit to revamped pollution under the condition that you approve a Mission Statement for it, and the guiding direction for it's design/rework.

**Comment by z3r0b0t** [comment]
> > @mitchej123 if i got your word under my comment now i merge it.
> 
> I'll commit to revamped pollution under the condition that you approve a Mission Statement for it, and the guiding direction for it's design/rework.

@mitchej123  Congrats on getting this approved / done ! I would really like to get involved / help in the pollution rework, I'd commit with you if you're looking for help for the same conditions. I have never developed with minecraft's codebase but know java to a certain extent, I work with c# everyday but did spend 1-2 years on java. I was kinda looking for the same conditions you're proposing here, basically a Product owner kinda role assigned to someone that can give a direction to this whole thing that can be followed through and through or a way to make the ideas approved in advanced so that the whole rework is not a proposition that will _maybe_ make it into production.

I don't know how it works around here to contribute, but I'm planning some time during my week nights / weekend for setting myself up and testing out a few things. Any help / pointers would be appreciated!

**Pull request merged**
