### PR TITLE
Fix typo in Readme

### PR DESCRIPTION
**Pull request by chill-was-taken**
Truly one of the pull requests of all time.

### CODE REVIEW

**Comment by chochem** [comment]
If you want to change readme dont do it here, but do it in the DAXXL repo. Specifically the readme template. Otherwise it will be overwritten in the next release.

**Review by Alexdoru — APPROVED** [review]

**Comment by Alexdoru** [comment]
crazy

**Comment by chill-was-taken** [comment]
> If you want to change readme dont do it here, but do it in the DAXXL repo. Specifically the readme template. Otherwise it will be overwritten in the next release.

Is there a page that says what you said? If not, I can create it because this info is important.

**Comment by chochem** [comment]
I just learned that by making the same mistake

**Comment by chill-was-taken** [comment]
For posterity, the page meant by "DAXXL readme template" is https://github.com/GTNewHorizons/DreamAssemblerXXL/blob/master/readme_template.md

**Pull request merged**
