### PR TITLE
Reenable angel wings

### PR DESCRIPTION
**Pull request by Chaoschaot232**
Referenz #10249

### CODE REVIEW

**Comment by miozune** [comment]
I didn't notice, but its instability is 100!? It's way more than other infusion recipes. Awakend Ichorium tools are 18, Elven Gateway Core and 8x solar are 20, Shard of Laputa is 48, and Deep Dark is 64. I'd suggest 20.

**Comment by Runakai1** [comment]
Wasn't general consensus to not enable angel rings

**Comment by Dream-Master** [comment]
> Wasn't general consensus to not enable angel rings

its a suggestion so feel free to discuss. The pr is not merged yet.

**Comment by Runakai1** [comment]
I think it needs to be gated the same as the gravisuit. I like the idea of having more flight options but: Angel ring should be as expensive as gravi chest plate because those are the main creative flight options. Gravi plates requires Fusion which needs several hours of ontime. Angel ring should be even a tiny bit more expensive because it doesnt need energy. Just a tiny bit because energy isn't a limiting factor on LuV+ mostly anymore.

**Comment by Chaoschaot232** [comment]
> I didn't notice, but its instability is 100!? It's way more than other infusion recipes. Awakend Ichorium tools are 18, Elven Gateway Core and 8x solar are 20, Shard of Laputa is 48, and Deep Dark is 64. I'd suggest 20.

Oh, totaly forgotten to adjusting this value. Will nerf it down to 30 which should then be fine :)

**Comment by Chaoschaot232** [comment]
> I think it needs to be gated the same as the gravisuit. I like the idea of having more flight options but: Angel ring should be as expensive as gravi chest plate because those are the main creative flight options. Gravi plates requires Fusion which needs several hours of ontime. Angel ring should be even a tiny bit more expensive because it doesnt need energy. Just a tiny bit because energy isn't a limiting factor on LuV+ mostly anymore.
> 
> The recipe seems expensive, I think the instability is good as is. I'm not that deep into TC to comment on complexity, if achieving those essentias/items/fusion stability is the same effort as getting to fusion

I would please you to compare how hard this suggestion is to get compared to what you have mentioned. I am open for every imput to make it competitiv with other creativ flight stuff but not to complicated :)

In discord I got shown the Aspect Terminus which wasn't in there before and it should one of the hardest ones to get. So was it toled to me. I could maybe rais the amount of this aspect with factor 1,5 or 2 (max)?
On the other side we have also still space for additional ingredients, maybe smth. from the nano suite recipes out there 🤔 

Hope to read a respone from you :)

**Comment by Runakai1** [comment]
> > I think it needs to be gated the same as the gravisuit. I like the idea of having more flight options but: Angel ring should be as expensive as gravi chest plate because those are the main creative flight options. Gravi plates requires Fusion which needs several hours of ontime. Angel ring should be even a tiny bit more expensive because it doesnt need energy. Just a tiny bit because energy isn't a limiting factor on LuV+ mostly anymore.
> > The recipe seems expensive, I think the instability is good as is. I'm not that deep into TC to comment on complexity, if achieving those essentias/items/fusion stability is the same effort as getting to fusion
> 
> I would please you to compare how hard this suggestion is to get compared to what you have mentioned. I am open for every imput to make it competitiv with other creativ flight stuff but not to complicated :)
> 
> In discord I got shown the Aspect Terminus which wasn't in there before and it should one of the hardest ones to get. So was it toled to me. I could maybe rais the amount of this aspect with factor 1,5 or 2 (max)? On the other side we have also still space for additional ingredients, maybe smth. from the nano suite recipes out there 🤔
> 
> Hope to read a respone from you :)

The idea of creative flight is being in the late middle game or something. There shouldn't be another item available before gravisuit.

**Comment by greesyB** [comment]
> In discord I got shown the Aspect Terminus which wasn't in there before and it should one of the hardest ones to get. So was it toled to me. I could maybe rais the amount of this aspect with factor 1,5 or 2 (max)? On the other side we have also still space for additional ingredients, maybe smth. from the nano suite recipes out there 🤔

Trying to gate the recipe with essentia is flawed because a normal wisp spawner can produce any type of essentia.

If angel wings are just creative flight with no bonuses (like boost from gravichest) then it seems like a strictly worse gravichest to me besides not needing power, which is a non-issue by the time gravichest is craftable. In that case gating it after gravichest seems unnecessary, but maybe others disagree.

As for the recipe the extremely primordial pearl is a nice touch, but not that difficult to make. I'd suggest including ichorium somewhere, and maybe tritanium if wanting to gate it past gravichest.

**Comment by Runakai1** [comment]
> > In discord I got shown the Aspect Terminus which wasn't in there before and it should one of the hardest ones to get. So was it toled to me. I could maybe rais the amount of this aspect with factor 1,5 or 2 (max)? On the other side we have also still space for additional ingredients, maybe smth. from the nano suite recipes out there 🤔
> 
> Trying to gate the recipe with essentia is flawed because a normal wisp spawner can produce any type of essentia.
> 
> If angel wings are just creative flight with no bonuses (like boost from gravichest) then it seems like a strictly worse gravichest to me besides not needing power, which is a non-issue by the time gravichest is craftable. In that case gating it after gravichest seems unnecessary, but maybe others disagree.
> 
> As for the recipe the extremely primordial pearl is a nice touch, but not that difficult to make. I'd suggest including ichorium somewhere, and maybe tritanium if wanting to gate it past gravichest.

You could argue that nano chest plate has creative flight since hover mode with the cost of energy, making the angel ring redundant. I'd agree with implementing the ring if titanium is used.

**Comment by Chaoschaot232** [comment]
> As for the recipe the extremely primordial pearl is a nice touch, but not that difficult to make. I'd suggest including ichorium somewhere, and maybe tritanium if wanting to gate it past gravichest.

This is an interesting idea which I'll go and investigate. Need to look these two items up and see what could suite :)
Maybe I'll replace the iridium rings with ichorium ones or add some ichorium to the recipe 🤔 
For titanium I have to look what could suit the recipe and the item in general :)

> Also, it seems like you just want early creative flight with what you said:

50:50 because then I could easly cheat them in in my own game but it is more fun when you have multiple items parallel available which inhert the same "power" but be made not identically. Gating and Hardness is then what counts to be achieved :)
I am glad to get not only feedback, I am happy to get also inputs to finalize the recipe ❤️

**Comment by Runakai1** [comment]
> > As for the recipe the extremely primordial pearl is a nice touch, but not that difficult to make. I'd suggest including ichorium somewhere, and maybe tritanium if wanting to gate it past gravichest.
> 
> This is an interesting idea which I'll go and investigate. Need to look these two items up and see what could suite :) Maybe I'll replace the iridium rings with ichorium ones or add some ichorium to the recipe 🤔 For titanium I have to look what could suit the recipe and the item in general :)
> 
> > Also, it seems like you just want early creative flight with what you said:
> 
> 50:50 because then I could easly cheat them in in my own game but it is more fun when you have multiple items parallel available which inhert the same "power" but be made not identically. Gating and Hardness is then what counts to be achieved :) I am glad to get not only feedback, I am happy to get also inputs to finalize the recipe ❤️

It's tritanium, not titanium. Made the mistake myself when I realized it's tritanium xD
However, I don't think for the sole purpose of early creative flight this recipe should be added. If you want a real addition to the game, make one that's properly gated. I don't like the idea of creative flight before the gravisuit, but I'm not the one deciding it.

**Comment by boubou19** [comment]
i personally don't see the point of reenabling the ring in the pack: you gate it too early and it messes with the flight options, you gate it too late, it's useless as fuck because Kami and Gravi are here to be better. Really you have tons of fly options and i sense that you want to reenable the ring just for the sake of it, which had been disabled sinces years (7 years ago, 1 year before i join NH 😂)

Also, could you put this into code? we want to eventually stop using the scripts, so if any new script entry could go into code that would be  good :)

**Comment by Chaoschaot232** [comment]
> It's tritanium, not titanium. Made the mistake myself when I realized it's tritanium xD
However, I don't think for the sole purpose of early creative flight this recipe should be added. If you want a real addition to the game, make one that's properly gated. I don't like the idea of creative flight before the gravisuit, but I'm not the one deciding it.

😹 they are easy to swapp xD - So then I'll lookup tritium instead of titanium :)

> i personally don't see the point of reenabling the ring in the pack: you gate it too early and it messes with the flight options, you gate it too late, it's useless as fuck because Kami and Gravi are here to be better. Really you have tons of fly options and i sense that you want to reenable the ring just for the sake of it, which had been disabled sinces years (7 years ago, 1 year before i join NH 😂)

I understand and accept your point that you don't want them to be reenabled and maybe there is some private interest from my side in this suggestion but on the other side why not? If it is at the end realy well balanced and competitive enough reenabling them shouldn't hurt.

> Also, could you put this into code? we want to eventually stop using the scripts, so if any new script entry could go into code that would be good :)

🤔 I remeber a guy who is called @Dream-Master ... he is evil since he has stated this the last weeks to me *caugh caugh*

Well, b2t, you are right that there are to much scripts out so I choosed for now the ExU script for faster testing purpose instead of recompiling every time a mod. When it is finaly accepted, for now, it could stay in the ExU script and I'll definitly then go an implement it into the correct mod (which one would it fit in 🤔 ). If this is fine for you (and all ohter) :)

**Comment by GTNH-Colen** [comment]
I don't see the harm in re-enabling it given its properly balanced.

**Comment by Runakai1** [comment]
> I don't see the harm in re-enabling it given its properly balanced.

Is it though? Seems like its much earlier available than gravi suit.

**Comment by Elisis** [comment]
It just seems like yet another option for flight that's not even necessary considering all the options we already have

**Comment by Chaoschaot232** [comment]
> It just seems like yet another option for flight that's not even necessary considering all the options we already have

Includes this also an option with flight for no cost in form of mana/energy (EU/RF) and a stable hover mode where you are not going down until the ground which is a pain in the ass when building in the air because you must then hit you fly key again to align back. This is one major problem where I am going to reject any items doing this because hover means hover and not hover + very, very, very ... very slowly falling down until the ground.



> I don't see the harm in re-enabling it given its properly balanced.

I'll push a new recipe with the materials mentioned earlier above soon. Would you like to take a look ob both recipes and tell me what look more balanced? I would appreciate it :)

**Comment by Dream-Master** [comment]
i makr this as draft till we finish the discussion if we realy need it.

**Comment by Runakai1** [comment]
I like the suggested recipe

**Review by Connor-Colenso — APPROVED** [review]

**Comment by Dream-Master** [comment]
@Runakai1 @Connor-Colenso is it balanced because with this you get creative flight.

**Comment by boubou19** [comment]
no one will craft it but whatever

**Pull request merged**
