### PR TITLE
Add pyrolyse quest

### PR DESCRIPTION
**Pull request by Elisis**
image
image
image

### CODE REVIEW

**Comment by Elisis** [comment]
I PRed it to new-quest to avoid any shuffling around of branches

Probably would be best to merge this before new-quest, if we do merge it

**Comment by miozune** [comment]
Doesn't making both tasks optional lets you complete the quest immediately?

**Comment by Elisis** [comment]
Couldn't think of a better way of including both machines. There're no rewards however so it's not like it benefits the player much

**Comment by Glease** [comment]
Set taskLogic to OR and use normal retreival task.

**Comment by Elisis** [comment]
Oh

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
