### PR TITLE
Change PG recipe

### PR DESCRIPTION
**Pull request by Prometheus0000**
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8154

### CODE REVIEW

**Review by Dream-Master — COMMENTED** [review]
not sure if this break balance. MAybe a core to expensive (but used in original recipe) but a Redstone block is a way to cheap

**Comment by Dream-Master** [comment]
will check recipe ingame

**Comment by Dream-Master** [comment]
@Prometheus0000 please change the redstone block to somethings more expensive. I merge it after

**Comment by Prometheus0000** [comment]
Made more expensive.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
