### PR TITLE
Remove Tinkers channel->nether brick faucet recipe

### LINKED ISSUE #9484: Bug in the "You are not prepared" quest
### Your GTNH Discord Username

MadRat96#9831

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Was doing "You are not prepared!" quest, crafted Seared Faucet using saw and casting channel. Expected quest to count these seared faucets as required.

### The Reality

Seared Faucets crafted from the saw and casting channel were not counted as required, only searing faucets crafted from searing brick are counted as required.

### Your Proposal

Instead of counting seared faucets crafted from the searing brick let the quest require any searing faucet - no matter how it was crafted

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by boathouse2112**
Fixes #9484.

Removes this recipe:

I can't figure out how to build the modpack to test yet, but it should work fine.

### CODE REVIEW

**Comment by Dream-Master** [comment]
Not remove recipes. It might not count for the quest but it work in  general .

**Comment by chochem** [comment]
@Dream-Master it has a different recipe that actually makes sense. this one doesnt, it mixes up the two materials. (hard to see in the picture above)

**Comment by Connor-Colenso** [comment]
Screenshot 2023-03-06 at 10 17 08

**Comment by Dream-Master** [comment]
@chochem ok this recipe is wrong but then we need to fix it instead to remove it.
The nether channel recipe need have ingots more and it need to be cut into nether faucet

**Comment by Dream-Master** [comment]
when this is fixed we can merge it.

**Comment by Connor-Colenso** [comment]
There is no nether casting channel so without adding one to Tinkers I don't see how the recipe can be fixed.
Screenshot 2023-03-06 at 10 35 58

**Comment by chochem** [comment]
I also remember it not existing. but apparently it was added (pic is RC3):
image

Who has been working on this? The recipe certainly needs adjusting if you compare it to non-nether.

image
image

so 1) remove the recipe as in this PR 2) adjust the nether channel recipe to be harder 3) add a saw recipe between the two nether items.

**Comment by chochem** [comment]
Lokks like @DrParadox7 is behind the addition. I guess they didn't we were changing recipes for this pack.

**Comment by Dream-Master** [comment]
@boathouse2112 your turn now :)

**Comment by boathouse2112** [comment]
Ok, removed the default nether channel recipe, and added one mirroring the normal channel. And made a saw + nether-channel -> seared-faucet * 2 recipe.
Tested in-game, and it looks ok.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
