### PR TITLE
Adjusting the requirements of the "Shake That Booty" quest

### PR DESCRIPTION
**Pull request by Eldrinn-Elantey**
47 casing is indicated in the quest, this is not enough. 51 is needed

### CODE REVIEW

**Comment by bombcar** [comment]
Does that account for muffler, maintenance hatch, and the extra casing mentioned if not using the dual energy hatch option?, etc? GT++ multis can be a bit confusing.

**Comment by Eldrinn-Elantey** [comment]
> Does that account for muffler, maintenance hatch, and the extra casing mentioned if not using the dual energy hatch option?, etc? GT++ multis can be a bit confusing.

Counting:

**Casing of multiblock sifter**

* 18x Large Sieve Grate right
* The lower layer of the machine is considered completely from Industrial Sieve Casing 5*5=25
* Two rings from Industrial Sieve Casing 16*2=32
* Housing without functional blocks 32+25=57

Total: 57x Industrial Sieve Casing

**Function blocks**

* 1x Controller
* 1x Input Bus
* 1x Output Bus
* 1x Energy Hatch
* 1x Maintenance Hatch
* 1x Muffler Hatch

Total: 6x Function blocks

57-6=51 Industrial Sieve Casing


P.S. The calculation assumes that the minimum allowable voltage for this multiblock is 128 EU/t

**Comment by draknyte1** [comment]
> > Does that account for muffler, maintenance hatch, and the extra casing mentioned if not using the dual energy hatch option?, etc? GT++ multis can be a bit confusing.
> 
> Counting:
> 
> **Casing of multiblock sifter**
> 
>     * 18x Large Sieve Grate right
> 
>     * The lower layer of the machine is considered completely from Industrial Sieve Casing 5*5=25
> 
>     * Two rings from Industrial Sieve Casing 16*2=32
> 
>     * Housing without functional blocks 32+25=57
> 
> 
> Total: 57x Industrial Sieve Casing
> 
> **Function blocks**
> 
>     * 1x Controller
> 
>     * 1x Input Bus
> 
>     * 1x Output Bus
> 
>     * 1x Energy Hatch
> 
>     * 1x Maintenance Hatch
> 
>     * 1x Muffler Hatch
> 
> 
> Total: 6x Function blocks
> 
> 57-6=51 Industrial Sieve Casing
> 
> P.S. The calculation assumes that the minimum allowable voltage for this multiblock is 128 EU/t

You require 4 output buses.

**Comment by bombcar** [comment]
It will run with 1 but you need 4 to get all products or something

**Comment by bombcar** [comment]
IIRC it's in the book, but we could update quest text.

**Comment by draknyte1** [comment]
`mCasing >= 35 && mOutputBusses.size() >= 4`

The 4 bus requirement has always been there, still is.

**Comment by Eldrinn-Elantey** [comment]
> `mCasing >= 35 && mOutputBusses.size() >= 4`
> 
> The 4 bus requirement has always been there, still is.

OK, I'll add 3 more blocks and which is the last one?

**Comment by Eldrinn-Elantey** [comment]
image

**Comment by bombcar** [comment]
It can take two energy hatches, or one (see quest text)

**Comment by Eldrinn-Elantey** [comment]
> image

Why is there no information about 4 output hatch in tooltips?

**Comment by draknyte1** [comment]
> > image
> 
> @draknyte1 Why is there no information about 4 output hatch in tooltips?

It was probably removed when all GT++ multis were migrated to StructureLib.

**Comment by Eldrinn-Elantey** [comment]
> > > image
> > 
> > 
> > @draknyte1 Why is there no information about 4 output hatch in tooltips?
> 
> It was probably removed when all GT++ multis were migrated to StructureLib.

Is it possible to fix it?

**Comment by bombcar** [comment]
Anything is possible - the code for that is .... where was I looking ...

https://github.com/GTNewHorizons/GTplusplus/blob/2fd8aaa45671c19af597b2a84201e0dfe08b9366/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_IndustrialSifter.java#L52

**Comment by Eldrinn-Elantey** [comment]
> Anything is possible - the code for that is .... where was I looking ...
> 
> https://github.com/GTNewHorizons/GTplusplus/blob/2fd8aaa45671c19af597b2a84201e0dfe08b9366/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_IndustrialSifter.java#L52

Will we close this request and open a ticket for a bug?

**Comment by draknyte1** [comment]
Fixed in https://github.com/GTNewHorizons/GTplusplus/commit/9e9d81a4e2667d9aeb3022d40fbe4a1972121cf9.

**Comment by bombcar** [comment]
Fixed above

**Pull request closed without merging**
