### PR TITLE
Implementation: Adds raw ores as a valid quest imput.

### PR DESCRIPTION
**Pull request by Ethryan**
Requires: [#2502](https://github.com/GTNewHorizons/GT5-Unofficial/pull/2502)

### CODE REVIEW

**Comment by Ethryan** [comment]
Think  I have edited all ore quest now @Dream-Master , this is just waiting on the main now.

**Comment by Dream-Master** [comment]
@Ethryan sure after 2.6.0 update

**Comment by D-Cysteine** [comment]
It looks like this PR removes these two MV quest files (under `Quests/` directory):

* `TantalumNether-AAAAAAAAAAAAAAAAAAAJeg==.json`
* `OverworldTantalu-AAAAAAAAAAAAAAAAAAAHKw==.json`

and adds this one:

* `TantalumOre-AAAAAAAAAAAAAAAAAAAHKw==.json`

However, this means that the quest ID `AAAAAAAAAAAAAAAAAAAJeg==` no longer exists, but it continues to be referenced by the MV quest line because the MV quest line was not updated in this PR. This is likely due to a conflict with the quest line format change PR:

* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/15749

The MV quest line folder should probably be updated to remove the `TantalumNether-AAAAAAAAAAAAAAAAAAAJeg==.json` quest, and also handle the rename of the `OverworldTantalu-AAAAAAAAAAAAAAAAAAAHKw==.json` quest to `TantalumOre-AAAAAAAAAAAAAAAAAAAHKw==.json` (this last step isn't strictly necessary, but it's good to keep things consistent). I can add a commit to this branch to do this, if you'd like; just let me know.

---

Fixing this should resolve:
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16277

**Comment by Ethryan** [comment]
Looks good

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
