### PR TITLE
Quest additions+fixes

### PR DESCRIPTION
**Pull request by Prometheus0000**
A few fixes, Dream asked me to add the books, and mostly adding quest stuff from #6161.

### CODE REVIEW

**Comment by yukieiji** [comment]
It's harder to see than the previous LuV quest line, is this okay @Dream-Master ?

prev:

after merging:


Also, why did you lower the tier of Radiohatch? It's a quest that's open to EVs, so I was going for the EV hatch.

**Comment by Prometheus0000** [comment]
It seems I forgot to add my last changes, the mysterious dust quest in the bottom left.

Also, I had a huge mess of a time getting stuff to fit right, feel free to try to open it up more after I send my last changes.

I lowered it because it's supposed to be HV, that's when the vat opens up? Plus I don't think there's any meaning in it being EV, it doesn't change anything really.

**Comment by Prometheus0000** [comment]
About the hatch, at hv it holds 1, but ev holds 2, but it still only uses 1 up at a time, so it'll just grab more from the stack (or lower amount) you put in. If you want to use long rods it would matter, but I think people would rather have the granularity that comes with the normal rods.

**Comment by yukieiji** [comment]
The EV is the tier that will unlock radioactive materials such as Uranium, and the reward is a rod of Uranium, so the quest of RadioHatch is set to EV.
If you think about it, RadioHatch's tier could be just about anything. Can't I do the RadioHatch task in any of the tiers?

**Comment by Prometheus0000** [comment]
Yes, it could be any of them, but the HV one is cheaper (and realistic to make unlike UV for example), plus they're actually worse as you go up the tiers for the reason I mentioned.

Would you actually make the EV one? I'd still use the HV one at UV, since there's no reason to make or use the higher tier ones.

Also, the first material on the list is Bismuth, from the Nether. Plus a bunch of misc ones I forget/don't know.

**Pull request merged**
