### PR TITLE
Remove PSS controller recipe

### PR DESCRIPTION
**Pull request by Prometheus0000**
See #7090.

I tried removing the LuV+ redox cell recipes, but there's no way to remove assembler recipes with MT. 😢 

It should probably wait until after 2.1.0.6 at least.

### CODE REVIEW

**Comment by Dream-Master** [comment]
There is. Still look into gt config. Set prcessing time of the recipe to 0

**Comment by Prometheus0000** [comment]
I'm not sure what you mean? Recipes aren't defined in a config file? Not to mention this is a GT++ recipe, not GT?

Do you mean overriding a recipe with another one that's the same with 0 time in the script file?

**Review by Dream-Master — APPROVED** [review]

**Comment by johnch18** [comment]
Based

**Comment by Alexdoru** [comment]
Removed the quests related to the PSS ?

**Comment by GTNH-Colen** [comment]
This is kinda ridiculous, a thread was made which was clearly in favour of NOT doing this so your response is an attempt at a stealth nerf? Very unprofessional.

**Comment by GTNH-Colen** [comment]
@Dream-Master Please undo this PR until further discussion can be had on the matter, it is not resolved.

**Comment by Prometheus0000** [comment]
BTW, I'm fine with it being reverted. I thought we'd be discussing it for _days_ at least.

**Comment by 0lafe** [comment]
This seems like a good change. LSC is more than enough, and we can't control the PSS

**Comment by botn365** [comment]
gt++ is on its way out anyway so i dont see the problem by removing it now

**Comment by iouter** [comment]
because player need a mod can be instead of gt++, not remove recipes only,

**Comment by 0lafe** [comment]
the LSC does that for power storage which is all that's being removed right now tho

**Comment by iouter** [comment]
LSC is tooooooooooooooooooooooooooo expensive, so it is not suitable for IV-UV use.

**Comment by 0lafe** [comment]
it's more expensive than the PSS for sure but it's very cost balanced. The storage is costly but the throughput is cheap, which is very fair

**Comment by GTNH-Colen** [comment]
The merits for or against the PSS are irrelevant, merging this without finishing out prior discussion in another thread is wrong and tantamount to a stealth nerf (esp when the vote was going heavily against doing it). The matter has been discussed internally by staff and agreed that it should be reversed for the time being.

**Comment by iouter** [comment]
Make a Lapotronic Capacitor(LUV) need :

1x Multilayer Fiber-Reinforced Circuit Board
32x Europium Foil
4x LuV-tier Circuit
36x2x Engraved Lapotron Chip
64x High Power IC
32x Advanced SMD Diode
32x Advanced SMD Capacitor
32x Advanced SMD Resistor
32x Advanced SMD Transistor
64x Fine Platinum Wire
4x Osmiridum Frame Box
24x Osmiridium Screw
L1/720x Molten Soldering Alloy

i don't think this is more fair

**Comment by core-exe** [comment]
It does not matter if it is cheap or not. LSC is not the substitude of PSS in IV stage. Many using PSS is because EV-LuV battery is way too expensive from it should be.

**Comment by GTNH-Colen** [comment]
Please direct further comments about PSS/LSC balance to #7090 or I will lock the thread, thanks.

**Comment by 0lafe** [comment]
it's really not tho? as someone who didn't use a PSS or an LSC, you get very good storage from the batteries for the cost. you really don't need much storage at all in those stages, and the LSC multi really is just meant for centralization, which it excels in

**Pull request merged**
