### PR TITLE
Meteor Changes and New Meteors

### PR DESCRIPTION
**Pull request by ScriptedPiky**
**Very important notes:**
More significant testing is required, however, this is quite promising so far.

So far this keeps most of the original/legacy meteors and will add several more (this will be constantly edited).

### CODE REVIEW

**Comment by bombcar** [comment]
You can mark it draft to (mostly) keep it from being merged 🤣

**Comment by ScriptedPiky** [comment]
**More meteor notes:** DO NOT rename the meteor config names 'TempOreMeteor<number>' to anything but this. Apparently will cause a crash and simply will not work. Not sure if it's possible to add a "README" file in the meteor file without also having it crash

**Comment by ScriptedPiky** [comment]
**Reconfirmation:** The crash was a result of some missing commas, whoopies. Will further test if the name change to the config actually does anything or not.

**Comment by ScriptedPiky** [comment]
I think I'm about done so far. I've ran out of ideas on what to do for newer meteors, but if anyone has any ideas, feel free to implement them or discuss them. All of this should be ready to go.

**Comment by GTNH-Colen** [comment]
Can we get a summary? There are a lot of commits here

**Comment by glowredman** [comment]
@GTNH-Colen The summary under "[Files changed](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/9389/files)" is actually pretty readable.

**Comment by ScriptedPiky** [comment]
I'm unsure how to summarize this, other than 'you can summon a lot more meteors, each has a costing item and costing LP amount in the files.' Unfortunately, you either have to know the item by memory or checking in-game and checking the file itself, as I cannot or do not know how to make it easily viewable in the .json files. I also can't add a .txt file there to make it simple and easy to find out. Blood Magic Meteors are not user friendly, it seems, heh. A lot of exploration for one to do.

Additionally, I'm heavily limited to just OreDict for blocks that can be applied for the meteor, making it impossible to get a wider range of the same block type with meta IDs (i.e. Enceladus Ice). I'm going to post a bunch of screenshots of these over the course of an hour or so once I fully test and gather all the necessary screenshots.

**Comment by ScriptedPiky** [comment]
Alright, these have been thoroughly tested for the most part and do work. This was quite fun but unbelievably tedious. Still has so much more potential.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
