### PR TITLE
Fixed the "Mundane Larch" quest

### PR DESCRIPTION
**Pull request by Eldrinn-Elantey**
The mandatory item and the optional item were mixed up in places

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Eldrinn-Elantey why you need 100 of commits to just change two lines of questbook ?

**Comment by Eldrinn-Elantey** [comment]
> @Eldrinn-Elantey why you need 100 of commits to just change two lines of questbook ?

I started my acquaintance with git when I started making changes to your modpack. I honestly don't know why it happened. I tried to figure it out, but the only thing that happened was to make sure that only these two lines were sent. The remaining commits are either leftovers from other edits or their cancellation. I still don't understand why they are listed here even though the repositories are synchronized

**Comment by chochem** [comment]
the reason is that you are doing a PR from your master which has a different history even if the files are identical. To avoid that make a branch based on upstream/master.

**Comment by Eldrinn-Elantey** [comment]
> the reason is that you are doing a PR from your master which has a different history even if the files are identical. To avoid that make a fresh branch based on upstream/master.

@chochem Is it done here?
image

**Pull request merged**
