### PR TITLE
Quests for the new steam multiblocks

### PR DESCRIPTION
**Pull request by Baerschen**
Things that still have to be done:
- [x] Info about the tier button of the multiblock preview and that upgrading to steel doubles processed items to 16 at a time
- [x] Washer description
- [x] Centrifuge description
- [x] Forge hammer description
- [x] Maybe adjust old quest text to match info added in the new ones
- [x] Finish Forge hammer quest when https://github.com/GTNewHorizons/GT5-Unofficial/pull/2736# is merged and nightly released
- [x] Fix typos
- [x] Add the right amount of items to the quests
- [x] As discussed in discord will move it to GT++tab
- [x] add output hatch to centrifuge
- [x] add a quest for the water pump since i think its a nice multi (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/16850#issue-2433655027)
- [x] Changed info of washer since it can be switched to simple washer
- [x] finish up the central quest with needed info for all multis

Pictures of all quests can be seen at the very bottom.

### CODE REVIEW

**Comment by Baerschen** [comment]
Currently looking like this:
image

**Comment by Baerschen** [comment]
e.g. steam centrifuge quest
image

**Comment by Dream-Master** [comment]
> e.g. steam centrifuge quest image

With a new pr you can add a fluid output hatch to collect fluids from centrifuge processes . Not merged yet.

**Comment by Baerschen** [comment]
image
image
image
image
Last picture is the central one and not yet finished but its coming along nicely (I think)

**Comment by Baerschen** [comment]
And the layout of the GT++ tab looks like this currently:
image

**Comment by Baerschen** [comment]
Here are all the finished quests:
image
image
image
image
image
image
image
image

**Review by Steelux8 — APPROVED** [review]
Looks good to me!

**Pull request merged**
