### PR TITLE
#6161 Finished ZPM-UHV quests. Needs testing however

### PR DESCRIPTION
**Pull request by Prometheus0000**
Please test. Do not merge to main, as I'll likely need to change stuff still.

Also changed LuV a little. (auto maint, cheaper circuits (moved), resonatic circuits)

### CODE REVIEW

**Comment by bartimaeusnek** [comment]
@Prometheus0000 just make it a draft if it shouldnt be merged.

**Comment by Dream-Master** [comment]
we created a own branch

**Comment by Prometheus0000** [comment]
Dream made it a separate branch, is that not good enough? And I don't know what a draft in github terms is anyway.

**Comment by Dream-Master** [comment]
yes it is. @Prometheus0000  all fine.If you done we do a pull request from branch to branch. No draft needed

**Pull request merged**
