### PR TITLE
Disabled overworld natura clouds

### PR DESCRIPTION
**Pull request by jackowski626**

### CODE REVIEW

**Comment by Prometheus0000** [comment]
I like having the clouds though, how about we have a vote?

**Comment by repo-alt** [comment]
> I like having the clouds though, how about we have a vote?

Seriously? Just turn on Realistic Sky texturepack..

**Comment by Prometheus0000** [comment]
Well, I _hate_ that stupid thing.

**Comment by Prometheus0000** [comment]
So no vote then?

**Comment by Dream-Master** [comment]
Why a vote? This clouds are ugly ? Any useful recipe or ingredient using clouds ?

**Comment by Prometheus0000** [comment]
Well, I don't think they're ugly, so not everyone agrees with that?

**Comment by Dream-Master** [comment]
lets do a vote @Prometheus0000

**Comment by Prometheus0000** [comment]
Do you want to make it or should I?

**Comment by mitchej123** [comment]
I dislike them, and they interfere with launching rockets.

**Pull request merged**
