### PR TITLE
Update quest to reflect upcoming HTGR changes

### PR DESCRIPTION
**Pull request by Pxx500**
image

### CODE REVIEW

**Comment by chochem** [comment]
can you also adjust 'Faster Lutetium Excitement'? I dont even know what to make of that now, from what I understand I guess it should just be about Th232 instead?

**Comment by chochem** [comment]
also, mandatory @Steelux8 as you want to know what happens to your quest tab :P

**Comment by Pxx500** [comment]
> can you also adjust 'Faster Lutetium Excitement'? I dont even know what to make of that now, from what I understand I guess it should just be about Th232 instead?
I am adjusting it right now

**Comment by Steelux8** [comment]
Please, do not do an HTGR rework and change other important lines before next stable. We have a lot of bugfixing and integration work to do to get the stable out, so I ask that this rework and the relevant quest changes are made after the stable is released.

**Comment by Pxx500** [comment]
Don't merrge this until
https://github.com/GTNewHorizons/bartworks/pull/193
https://github.com/GTNewHorizons/GoodGenerator/pull/76
are merged

**Comment by Pxx500** [comment]
image
image
image
image

**Pull request merged**
