### PR TITLE
Remove IV Repellator from IV lootbag

### PR DESCRIPTION
**Pull request by Elisis**

### CODE REVIEW

**Comment by Dream-Master** [comment]
Add something back so the balance and chance of the loot bag not changed

**Comment by leagris** [comment]
> _ No description provided. _

A few words, mention of discussion and reason for this change would give ground to this PR to stand on.

**Comment by Elisis** [comment]
Ah, my bad. It's because it could be disassembled for the emitters which made it kinda OP to get

**Review by Dream-Master — APPROVED** [review]

**Comment by leagris** [comment]
Or as already envisioned by just laying a persistent NBT tag like `gift` and having disassembler refuse to disassemble loot tagged stuffs, that would be enough.

Having looted magines and items with special properties not present in regularly crafted version, would be something akin to enhance gameplay by enabling many different balance adjustments levers like:

- Cannot disassemble.
- May break after some time.
- May have different efficiency, speed than its crafted counterpart.
- May have different durability than its crafted counterpart.
- May disassemble into specific listed parts (legit but limited re-use of the crafting ingredients NBTs). Makes it possible to create loots of "unknown technology" machines crates that can be turned to specific components or raw materials if disassembled or crushed.

Most of this re-use of previous implementation of crafting ingredients NBT but for looted items/machines from Gregtech would give more possibilities while not requiring additional developments. (maybe some work to enter those new loots with designated ingredients).

Other items or machines, since crafted without NBT ingredient, would continue to benefit optimised disassembly and reduced payload. Only specific loots would have extra data.

**Comment by boubou19** [comment]
nbt tags for special ways of obtention sucks: you turn your stuff to be unstackable, which causes a lot of issues in automation.

**Comment by Steelux8** [comment]
This was approved... IV lootbags are one of the few helping hands in the huge grind that is the IV tier, it keeps getting harder and longer, and lootbag nerfs contribute to that.

**Pull request merged**
