### PR TITLE
Update Backpack.zs

### PR DESCRIPTION
**Pull request by Yakameen**
Implemented fix from https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/7137

### CODE REVIEW

**Comment by Yakameen** [comment]
Actually, please pause this. I want to investigate the crash happening first.  https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7266

**Comment by Dream-Master** [comment]
Sure set it to draft

**Comment by Yakameen** [comment]
This is not affected by the same crash as adventure backpacks were affected by since the inventory is saved in a text file and referenced instead of stored directly in nbt.

**Comment by Dream-Master** [comment]
@Yakameen did you test the whole stuff ?

**Comment by Yakameen** [comment]
Yes, I tested crafting a small backpack, put stuff in it and upgrading it all the way to big also I added dye to it at each step with no issues.
The bags have NBT data that look like below. The code added simply copies the Backpack-UID between crafting recipes. There is no crash if the bag does not have an ID assigned to it. 
`<Backpack:backpack:202>.withTag({"backpack-UID": "325c7a8c-343c-4ccc-b08e-f9b1c5792c95", name: "item.backpack.big_red.name"})`

**Review by Ethryan — APPROVED** [review]
Good enough testing for me

**Pull request merged**
