### PR TITLE
Improve and fix space quest

### PR DESCRIPTION
**Pull request by yukieiji**
- Improve rocket fuel quest line design
- Scale up some rocket fuel quests
- T6-T8 Rocket quests to be arranged similarly to other rocket quests
- Add T6-T7 dungeon quests
- Add some quest reward(We may need to discuss some of this)
- Fix T5 Heaby Duty Plate Quest
- Rename Rocket Tier 6-8 Requirements Quests to Tier 6-8 Heavy Duty Plate Quests
- Change the text that Rocket Tier 6-8 Requirements Quests to the same one as the other Heavy duty plate quests

ScreenShots:
prev:

After Merge:

### CODE REVIEW

**Comment by Dream-Master** [comment]
@yukieiji if two people working on quests at the same time we get issues with merging. Can you merge the newest changes from prometheus in your branch to make it compatile ?

**Comment by yukieiji** [comment]
OK

**Comment by Prometheus0000** [comment]
The quests along the bottom are seriously uneven, could you fix that? Also, did you add quests for _new_ rocket components? Were there no new ones for the T6, I can't remember?

**Comment by yukieiji** [comment]
Which part is uneven? Is this the part of the T7 Rocket Quest?
The Tier 6 Requirements rocket quest was split into Schematic quest and Heavy Duty Plate Quest, just like the T4 rocket quests.

**Comment by Prometheus0000** [comment]
84578698-b353c280-ae02-11ea-9e79-390658656213

> Were there no new ones for the T6, I can't remember?

^ If there's no new components it's fine, I just thought you might've forgotten them.

**Comment by yukieiji** [comment]
Now at last check, the reload was not working.
Can you turn it back on?

**Pull request merged**
