### PR TITLE
Issue #9408 fix

### PR DESCRIPTION
**Pull request by ApexPredaturr**
Updated requirements for the 'I Know His Name' quest...hopefully this was done properly this time...

### CODE REVIEW

**Comment by Steelux8** [comment]
image

Many quests were changed in the JSON file like this, which would explain the amount of lines added and deleted. It seems unintended, and probably breaks the questbook. I can't figure out what this change to all quests means, or why it happened.

**Comment by Dream-Master** [comment]
This pr contains to many changes so i guess it is wrong. Loaded the latest version of Questfile from Github and reload it ingame. Add your changes and save the file.

**Comment by Dream-Master** [comment]
@ApexPredaturr make a new pr with less changes. Thanks

**Comment by miozune** [comment]
Superseded by #10428

**Pull request closed without merging**
