### PR TITLE
Add alternate recipes for reflector parts for mass crafting

### PR DESCRIPTION
**Pull request by Houstonruss**
Before: requires wrenches
image
After: Assembler recipes OR Wrench recipes
image

### CODE REVIEW

**Review by bartimaeusnek — APPROVED** [review]

**Comment by Houstonruss** [comment]
Also to note: this made the fusion coil recipe calculate almost instantly in AE for 100000 of them. I say this is an upgrade.

**Comment by Dream-Master** [comment]
let's pack this in code and add a control circuit in slot 9

**Comment by repo-alt** [comment]
If neutron reflector is not used in other assembler recipes, better not add the circuit

**Comment by bartimaeusnek** [comment]
> 
> 
> If neutron reflector is not used in other assembler recipes, better not add the circuit



> 
> 
> let's pack this in code and add a control circuit in slot 9

I don't see why you'd want the circuit in here either...

**Comment by Dream-Master** [comment]
I had massive problems with iron tanks the recipe not shown because other recipes have no circuits. So i add circuits as standard to prevent the assembler not show all recipes.

**Comment by Houstonruss** [comment]
The reflectors have no conflicting recipes. They're only used for higher tier reflectors

**Comment by Dream-Master** [comment]
let me put this in code to reduce loading time.

**Comment by Dream-Master** [comment]
Added via code
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/44e2adad55f304d5a39e95f17e3e3f7f7bb4627c

**Pull request closed without merging**
