### PR TITLE
DEFC+draconic schematics quest and more quest changes

### PR DESCRIPTION
**Pull request by chochem**
- added new Draconic Evolution Fusion Crafter quest which gives the schematics as reward and is repeatable for the cost of 64 cores each time. This makes the higher tier cores craftable again.
- turn endgame goals visible (Colen intended to do so in the first place in his rework)
- small number fix to europium quest

### CODE REVIEW

**Comment by boubou19** [comment]
it's lacking one thing: the removal of the whole questline for the DE cores 😄

**Comment by chochem** [comment]
making it a draft for now as boubou wants to do a more comprehensive rework right now.

**Comment by Dream-Master** [comment]
No schematics as reward please

**Comment by Dream-Master** [comment]
The schematic are not consumed so you need them once

**Comment by King65868** [comment]
Might need them once, but there is always a chance of losing them

**Comment by Dream-Master** [comment]
sure but we not need a repeatable quest

**Comment by chochem** [comment]
no longer relevant it seems

**Pull request closed without merging**
