### PR TITLE
Quest: ETOOMANYKEYS: add a note about the waypoint manager

### PR DESCRIPTION
**Pull request by chill-was-taken**
This PR adds a single line with a Shift+B command.

This shortcut is not mentioned in any other quest or controls, but it saves a ton of time and nerves if you use teleportation because it allows you to instantly open Waypoints rather than first open the JourneyMap and then manually click on the Waypoints button.

### CODE REVIEW

**Comment by chill-was-taken** [comment]
```
$ git diff head^ --word-diff
[...]
Place the item you are holding on the block you are looking at\n\nJourneymap\n
B - Create a 
[-Waypoint\nJ-]
{+Waypoint\nCtrl+B - Open the Waypoint Manager\nJ+}
 - Open Fullscreen Map
[...]
```

**Comment by chochem** [comment]
isnt that quest completely outdated with the removal of all the default keybinds? would need a test on a clean 2.3.3 install with default configs

**Comment by chill-was-taken** [comment]
I've tested it on a fresh install of 2.3.3. The B hotkey was there, and Ctrl+B worked too.

**Comment by chochem** [comment]
ah looks like someone fixed it. probably alex how did the change. this will be easier to see with the separate files going forward :P

**Review by chochem — CHANGES_REQUESTED** [review]
can you fix the basic grammer? at least unbinded -> not bound, binded->bound

**Comment by chill-was-taken** [comment]
sure

**Comment by chill-was-taken** [comment]
$ git diff head^ --word-diff
`
"desc:8": "ERROR: Too many keys to fit a 104 key keyboard.\n\nThere are [-lots of-]{+many+} keybinds in this [-modpack, to-]{+modpack. To+} avoid [-conflicts-]{+conflicts,+} most of them are [-unbinded-]{+unbound+} by [-default and only those-]{+default. Only the ones+} available from the start[-of the game-] are [-binded.\nHere-]{+bound.\nHere+} is [-a-]{+the+} list of what some of them do :\n\n\nBetterQuesting\nGRAVE - Open Questbook\n\nBattlegear\nR - Draw Weapons - It\u0027s a second hotbar that holds weapons\n\nDraconic Evolution\nV - Place the item you are holding on the block you are looking at\n\nJourneymap\nB - Create a [-Waypoint\nJ-]{+Waypoint\nCtrl+B - Open the Waypoint Manager\nJ+} - Open Fullscreen Map\n\u003d - Zoom In (works on minimap too)\n- - Zoom out\n\nInventory Tweaks\nR - Sort Inventory\n\nShare Where I am\nINSERT - Places a temporary beam where you are looking at that will be seen by you and other players\nSHIFT + INSERT - Places a temporary beam where you are that will be seen by you and other players\nCTRL + INSERT - Shares with other players the position you are looking at\nCTRL + SHIFT + INSERT - Shares with other players your position\n\nWaila - Shows [-informations-]{+information+} of what you are looking at\nNUMPAD1 - show/hide the Waila HUD\nNUMPAD3 - shows how to craft what you are looking at\nNUMPAD4 - shows the crafting usages of the thing you are looking at\n"
`

**Review by chochem — APPROVED** [review]
thanks!

**Pull request merged**
