### PR TITLE
docs(quest): Rubber Sheets: mention Piston Boots

### PR DESCRIPTION
**Pull request by chill-was-taken**
Rephrase the Rubber Sheets quest to mention Piston Boots.

Also clarify the main usage of Rubber Sheets at this stage.

Remove the mention of other things that are crafted not as often.

### CODE REVIEW

**Review by chochem — CHANGES_REQUESTED** [review]
cheaper? you just mean steam or what? pretty sure its the same ratio.

instead of 'look up the quest' better name the questline they should check out!

**Comment by chill-was-taken** [comment]
Yes, I meant steam.
Tin Cable in Alloy Smelter is 700 EU ULV in 5 sec.
Rubber Sheet in Alloy Smelter is 60 EU ULV in 0.5 sec. Rubber Sheet is then manually crafted with Tin Wire at no cost.
Both recipes spend 2 rubber bars.

**Review by chochem — APPROVED** [review]
thanks

**Comment by chill-was-taken** [comment]
Added "in EU" in the last force push to clarify your first point.

**Comment by chochem** [comment]
maybe 'power'? since this is still steam age

**Comment by chill-was-taken** [comment]
True, one second.

**Pull request merged**
