### PR TITLE
blacklist some space ore and lanth nuggets dupe recipe

### PR DESCRIPTION
**Pull request by GlodBlock**

### CODE REVIEW

**Review by boubou19 — CHANGES_REQUESTED** [review]
some of them are unoffensive and bedrockium dupe is harmless too

**Comment by BlueWeabo** [comment]
Bedrockium isn't too op. You need to use tons of essentia to get the bedrockium needed. And only ways to get this kind of essentia is through platinum or wisps.

**Comment by boubou19** [comment]
for bedrockium, see my comment here: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10147#issuecomment-1098544639

after tantalum, except bedrockium, they are all kinda useless (except duralumin that is used a bit maybe)

Also Mythril is kinda useless too

**Comment by GlodBlock** [comment]
some are lanth materials that may going to be used in future.
the space ore part can be reverted if you really think they are useless, tho they have very good turbine values.

**Review by boubou19 — APPROVED** [review]

**Review by BlueWeabo — CHANGES_REQUESTED** [review]
I don't see any point in blacklisting stuff like aluminium, chrome, ect. Which are materials easily accessible and allows people, which go into TC early to get some benefits for a higher chance to destroy their base with the current warp effects.

Not to mention that to first dupe a material you need to have gotten at least one of the materials as an ingot.

I can understand about lanth lines, but those materials don't have a meaningful production until DD portal. So the dupling is an alternative after you have gotten some of the material. So you will not be skipping the lanth line.

The essentia costs to upkeep these resource productions are very hard to meet. One cannot easily make the needed resources without giving up some other material and a lot of TPS.

**Comment by GlodBlock** [comment]
the lanth line material still should be blacklisted imo. currently some lanth material are only used in very small amounts, so if it is dupable, people will only manually make some and turn to dupe recipe

**Comment by BlueWeabo** [comment]
People will manually make some if they know about the duping recipe. I am not sure if the recipe is shown after the nei update, which allowed us to see non-unlocked recipes.

Many people would still prefer to do the lanth line than set up duping as getting the essentia can seem annoying.

I can let lanth line materials to stay blacklisted, but some other not so much.

Why are Gallium, Tantalum and Neodymium still black listed? Sure they aren't used a lot, but they are much easier to get later in game so it's a good way for those, which can go through TC get some benefit from it. I must remind that TC starts at MV where one can start these dupes, which won't benefit those at LV where Galium is used first.

Neodymium you get tons when you enter EV cus you have been to the moon, so it doesn't really matter if there is a dupe.

Tantalum is mainly used in EnderIO, which is already a bit of a pain to get. It does give an alternate smd capacitor recipes which isnt even worth using.

**Comment by boubou19** [comment]
i'll add that xp buckets is also a thing if really you want to get stuff

**Review by BlueWeabo — APPROVED** [review]

**Pull request merged**
