### PR TITLE
Should remove the IC2 Hammer recipes

### LINKED ISSUE #15074: Remove IC2 forge hammer plate recipes
### Your GTNH Discord Username

vovassgreat

### Your Pack Version

nightly 248

### Your Server

unrelated

### Java Version

Java 21

### Type of Server

None

### Your Expectation

IC2 forge hammer is disabled in the modpack. The recipes that use it should not be displayed in NEI and in best case should be removed completely. 
I dont recall if i saw these recipes in NEI on older versions.

### The Reality

image-53

### Your Proposal

Remove these recipes.
Issue submitted on behalf of EvgenWarGold.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

### PR DESCRIPTION
**Pull request by Ethryan**
At least according to the information from the config.

closes #15074

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Ethryan why we not remove all ic2 recipes?

**Comment by Ethryan** [comment]
No clue, but if I do, it will probably conflict with stuff in GTNHCore.

**Comment by Dream-Master** [comment]
where is the part with the plates and the hammer ?

**Comment by Ethryan** [comment]
Thats already removed in theese config, it was there in the original one.

**Comment by Dream-Master** [comment]
we need to test if recipes are missing and need to be readded first. but yea i dont think we using original ic2 recipes so far ik

**Comment by Ethryan** [comment]
I added the configs with all recipes reomved. If it works, we can remove the IC2 recipe remover in GTNHCore.

**Comment by Dream-Master** [comment]
> I added the configs with all recipes removed. If it works, we can remove the IC2 recipe remover in GTNHCore.

good idea. downside if somone forget to add those changed configs all recipes are back ingame

**Comment by Ethryan** [comment]
It is new files that don't even exsist unless they are used, so they shouldn't even override any already existing setup.

**Pull request merged**
