### PR TITLE
Remove Dead Servers

### PR DESCRIPTION
**Pull request by Rexicon226**
I was looking some more through the list and noticed that these servers aren't up anymore. If it's just a temporary thing ignore this PR :D. Just wanted it to be cleaner.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Rexicon226 are the other server up ? i mean from Modded Minecraft Club ?

**Comment by Rexicon226** [comment]
@Dream-Master Yes, when I checked earlier today, they were all up except the removed ones.

**Review by Dream-Master — APPROVED** [review]

**Comment by Dream-Master** [comment]
@Rexicon226 there ara another file where the server is listed default server list json. Can you remove teh entries there too ?

**Comment by Rexicon226** [comment]
You got it, also I literally just checked and the other servers are up!

**Comment by Dream-Master** [comment]
> You got it, also I literally just checked and the other servers are up!

can you remove the two lines in file <https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/defaultserverlist.json> as well ?

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
