### PR TITLE
Remove/hide EC2 items, and other useless AE2 related items. Also change TE recipes

### PR DESCRIPTION
**Pull request by Prometheus0000**
Vibration chambers are useless, so removed. Grinder was removed already, so removed the related gear items.

Otherwise, see #7927.

Quests need to be adjusted after.

### CODE REVIEW

**Review by GTNH-Colen — COMMENTED** [review]
Looks good.

**Comment by Dream-Master** [comment]
I like to see a implementation of staff in ae2 first and remove ec after it. @repo-alt any future plans on this ?

**Comment by repo-alt** [comment]
It is kind of stupid jub to move working stuff, since there are quite a bit remaining in EC2. That is, - I tried the moving and found it possible, but not quite trivial process, so I think this job has too few benefits to be worth the efforts.

**Comment by Dream-Master** [comment]
@repo-alt so you vote for drop the mod without any alternative way store fluids in ae systems ?

**Comment by repo-alt** [comment]
Nah, I vote to disable half of the mod and leave it be.

**Comment by Dream-Master** [comment]
@Prometheus0000 @repo-alt ok but we need to do this inside the mod not with scripts  that it not loadedn all the unsed stuff.

**Comment by repo-alt** [comment]
Sure, but I thought the idea was to make disabling recipes a first step, and then disable the blocks themselves (if that is even necessary, since, as I said, SSP users have all the right to kill their TPS). Main concern now is to disable recipes and not break anything else, like ThaumicEnergistics recipes.

**Comment by Dream-Master** [comment]
Ok we can make a server script that disable ec2 stuff and let them enable in sp. Otherwise we decided for all players what they should do. @Prometheus0000 we should make a server branch and a client branch.

**Comment by Prometheus0000** [comment]
I have no idea how to make a 'server script'. I've edited the scripts to remove the recipes and hide the items, my work here is done. 

boubou and colen were complaining about people using fluid ae and lagging the servers, so I decided to do this quickly. EC2 is not in java, so I don't even want to touch it, so I'm not disabling items/mechanics in the mod myself.

Additionally, my understanding was that we were removing this stuff from SP as well. Altering the quests in such a way as to have them valid for both having and not having EC2 fluid stuff would mean having two versions of the questbook, which I'm not doing.

**Comment by Dream-Master** [comment]
Ok i can make new branches for server and client. And you can write in the book that this are disabled on server so not a big deal. Not need two versions of Quest book.

**Comment by Prometheus0000** [comment]
OK

**Comment by Prometheus0000** [comment]
Make sure to separate the 'this is useless so it's removed' removals from the 'this causes lag so it's removed' removals. Some things should still be removed in SP that aren't about fluid ae:

Vibration chamberx3 are not deisgned for 10x power use, walrus has some kind of rendering bus, blast resistant drive is crazy buggy, the part fixtures of power and drive had some problem I forget or were useless, the portable fluid thing I couldn't think of any use case for to leave it enabled, the 3 gear items have no use because the ae2 grinder is disabled.

**Comment by Prometheus0000** [comment]
Did anyone ever do this?

**Pull request closed without merging**
