### PR TITLE
minig pipe - conversely

### PR DESCRIPTION
**Pull request by MotiasF33**
before pr
изображение

### CODE REVIEW

**Comment by repo-alt** [comment]
What is it for?

**Comment by MotiasF33** [comment]
> 
> 
> What is it for?

for crafting: tip to regular mining pipe

**Comment by repo-alt** [comment]
Indeed, and what would you need that for?

**Comment by MotiasF33** [comment]
> 
> 
> Indeed, and what would you need that for?

After drilling rig working remain pipe - last from it is TIP , recipe is needed to continue using the used pipes

**Comment by repo-alt** [comment]
Ah, I see, you posted the picture of the current state, which is of course wrong.

**Review by repo-alt — APPROVED** [review]

**Comment by Dream-Master** [comment]
Please add the old recipe back so we have a conversion recipe for both pipes @MotiasF33

**Review by Dream-Master — APPROVED** [review]

**Comment by Prometheus0000** [comment]
@MotiasF33 See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/6790
Your PR caused the other one to not work. And you can't place down the mining pipe tip either?

> After drilling rig working remain pipe - last from it is TIP , recipe is needed to continue using the used pipes

How? They keep running anyway?

**Pull request merged**
