### PR TITLE
Extreme Industrial Greenhouse quest

### PR DESCRIPTION
**Pull request by kuba6000**
image
image
image
image

### CODE REVIEW

**Comment by glowredman** [comment]
Also it might be a good idea to have this quest be displayed in the farming tab. Multiblock tab is fine but imo IV tab is not really fitting.

**Comment by kuba6000** [comment]
Well the farming station quest is in HV tier tab, thats why i put it there as well

**Comment by glowredman** [comment]
That I can understand because (if I remember correctly) it is grouped together with the more advanced EnderIO stuff and maybe even predates the farming tab. Although it too might be more fitting in the farming tab

**Comment by chochem** [comment]
the enderio one is more versatile in some ways and does tree chopping for example. That is not exactly a farming/cooking thing.

**Comment by kuba6000** [comment]
Ok, i moved it to farming tab

**Comment by GTNHAfx237v7** [comment]
What does it mean „you can’t Farm two crop types at the Same Time?“ I remember you posting screenshots with up two four different types in there. Or should it say „you cannot harvest two or more crop types at the same time?“

**Comment by kuba6000** [comment]
It means that you can't farm IC2 crop and normal one at the same time.

**Comment by kuba6000** [comment]
I changed it to be more clear
image

**Comment by GTNHAfx237v7** [comment]
Much better, thx

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
