### PR TITLE
Fix bucket dupe in hazmat repair

### PR DESCRIPTION
**Pull request by Glease**
#6973

### CODE REVIEW

**Review by Ethryan — APPROVED** [review]

**Comment by Dream-Master** [comment]
@Ethryan did you run a test in SP and and MP ?

**Comment by Ethryan** [comment]
No, i only tested it in SP, it works as intended there.

**Comment by Dream-Master** [comment]
kk

**Comment by Dream-Master** [comment]
maybe we can try give back() without the bucket in the code ?

**Comment by Ethryan** [comment]
It works @Dream-Master , no change needed you still get 1 bucket back. it isn't duping anymore.

**Pull request merged**
