### PR TITLE
add a discord button on the main menu

### PR DESCRIPTION
**Pull request by boubou19**
normal:

hovering the discord button:

discord link:

### CODE REVIEW

**Review by glowredman — CHANGES_REQUESTED** [review]
I think the placement looks off, in my opinion one of the corners (preferably at the bottom) would be better

**Comment by boubou19** [comment]
at the same level as the quit message?

**Comment by glowredman** [comment]
For example (ofc with equal distance to both sides)

**Comment by boubou19** [comment]
well, it does not scale well: if you use a little scale of the gui, then you'll have it more next to the button column than the left border, as it's defined by a position offset from the Multiplayer button. Here is an exemple of what i mean:

I changed my gui scale from auto to small to get this. But it seems to be an issue of the base menu, so i don't know if we can really change that. So i need to know if the space between the column and the discord button is good enough, or if i should put it more to the left.

**Comment by glowredman** [comment]
Afaik it's possible to have a corner be 0/0, but the last time I used CMM was some years ago

**Comment by boubou19** [comment]
So you want it full corner? not with some space between the discord button and the borders?

**Comment by glowredman** [comment]
No, not *full* corner but idk 10 or so pixels from both sides. Alternatively not as an icon, but as an entry between language and mods - though ther might be a spce problem on large GUI scales

**Comment by boubou19** [comment]
I put a border of 20 from the bottom left corner, but for the small scales, it seems weird:
small

normal

large

auto

**Comment by glowredman** [comment]
I see what you mean, I think the smaller scales look weird in general though. Maybe you can make the distance larger for the smaller scales? All in all it looks better than in the beginning though. Some other people should probably look at this too.

**Comment by boubou19** [comment]
Same gui scale (normal), just the size of the window changing:
maximized window:

reduced window:


It behaves too weird, so i think i'm gonna set the position of the button as an offset of one of the other buttons. The question is which one? I put the button next to the multiplayer because of the community aspect. But if you think it looks weird, then what other button should i use?

**Comment by glowredman** [comment]
I think the best solution would be to make it a button like all the other, though as your last screenshot shows - there is no space.
I'd base it off of the "Quit" button, because the Discord butoon is not at some random height then.
Or:
If you can scale the icon, I'd make about as alrge as the text and put it left to one of the other buttons (the x coordinate would of course be influenced by the other buttons size). Again the "Quit" button would not neccessaryly the best fitting, but - i think - the best looking.

**Comment by Prometheus0000** [comment]
What if they accidentally hit quit instead? It takes a long time to load in.

**Comment by glowredman** [comment]
That is indeed a problem, but do you have a better idea than making sure there is some space between the two buttons?

**Comment by Prometheus0000** [comment]
Look at some other packs and copy what they do?

**Comment by boubou19** [comment]
I have 0 reference for the other packs, but if you give me some exemples, i can try to replicate it

**Comment by Prometheus0000** [comment]
Maybe later, I'm testing fixing things.

**Comment by glowredman** [comment]
From what I remember, most of the time they either integrate it into the "main" button set or put it in a corner. I'm starting up some packs now, I'll post the examples here

**Comment by boubou19** [comment]
I tried to mess with it on the same level as the "quit" button, but when it looks fine on a scale, if i maximize the window or if i use the reduced window, then it looks weird. I guess we need to integrate it in the button column. 1 small button could look weird in the button column, but we could use the same line to put several buttons: 1 for the discord button, 1 for a github button, and maybe 1 for the official website? I would place them on top of the button column. What do you think?

**Comment by Prometheus0000** [comment]
Small
image
Normal
image
Large
image

**Comment by Prometheus0000** [comment]
Small
image
Normal
image
Large
image

**Comment by glowredman** [comment]
**All normal@1080p**
FTB Infinity Evolved Skyblock
grafik
FTB Ultimate Reloaded
grafik
Minecraft Breakdown 3.2
grafik
Space Astronomy
grafik


@boubou19 Yes I think that's a good idea, though there are some questions then:
- Do 2/3 buttons with text fit in the same row?
- If not, can they (partially) be replaced by icons?
- If yes, does the rest look odd, becuase they *don't* have icons?

**Comment by glowredman** [comment]
Also, I wouldn't put it on top. SP, MP and maybe options should always be the first ones. I think above or below mods would be fine

**Comment by boubou19** [comment]
Which one do you prefer?

**Comment by glowredman** [comment]
I think the top one looks better

**Comment by boubou19** [comment]
then i'll make top one then :D

**Comment by Prometheus0000** [comment]
The top one looks better, but certainly doesn't look as good as the other pack's stuff.

**Review by glowredman — APPROVED** [review]

**Comment by glowredman** [comment]
Agree, though i guess getting to that standard would require some serious changes to the main menu. I would appretiate such changes, but I wouldn't invest time myself and I don't expect that from others either

**Comment by boubou19** [comment]
small scale:

normal scale:

large scale:

auto scale:

hovering the gtnh website icon:

hovering the discord icon:

hovering the github icon:


github icon link is : https://github.com/GTNewHorizons/NewHorizons/issues
website link is : https://www.gtnewhorizons.com/
discord link is : https://discord.gg/EXshrPV

**Comment by Prometheus0000** [comment]
I agree, but I was hoping we could just borrow the format from another pack, however they do it.

**Pull request merged**
