### PR TITLE
update stack sizes

### LINKED ISSUE #8981: Adjust stack size on some items from 16 to 64
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.1.0

### Your Proposal

We made ic2 seeds stack in https://github.com/GTNewHorizons/Hodgepodge/pull/33

We made ingots stack to 64 in #8613

We should make the following items stack to 64 also:

- Snowballs
- Ender pearls
- Eyes of Ender
- Eggs

### Your Goal

As far as I can tell there's no gameplay reason to limit these (unlike say the TC hearts where the stack size of 10 limits how many hearts you can get from them).

It's just vanilla things.

### Your Vision

Hodgepodge these to 64

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

### PR DESCRIPTION
**Pull request by bombcar**
fix #8981

### CODE REVIEW

**Comment by Dream-Master** [comment]
Was there a vote ?

**Comment by bombcar** [comment]
> Was there a vote ?

I don't have perms to do a vote in #vote but I'm open to anything.

The one thing I did notice is that this DOES affect the anchors if you do NOT have them configured to allow automatic pearl insertion. @boubou19 what is set on the officials?

**Comment by glowredman** [comment]
Looks good, although it would probably better to do this in code:
```java
net.minecraft.init.Items.ender_pearl.setMaxStackSize(64);
net.minecraft.init.Items.egg.setMaxStackSize(64);
net.minecraft.init.Items.snowball.setMaxStackSize(64);
```
The Crops++ item's stacksize should be changed [here](https://github.com/GTNewHorizons/Crops-plus-plus/blob/master/src/main/java/com/github/bartimaeusnek/cropspp/items/CppBerries.java#L27).

**Comment by Dream-Master** [comment]
@bombcar @glowredman https://github.com/GTNewHorizons/GT5-Unofficial/pull/778

**Comment by Dream-Master** [comment]
loading screen cfg need to be seperated

**Comment by bombcar** [comment]
> Looks good, although it would probably better to do this in code:
> 
> ```java
> import net.minecraft.init.Items;
> Items.ender_pearl.setMaxStackSize(64);
> Items.egg.setMaxStackSize(64);
> Items.snowball.setMaxStackSize(64);
> ```
> 
> The Crops++ item's stacksize should be changed [here](https://github.com/GTNewHorizons/Crops-plus-plus/blob/master/src/main/java/com/github/bartimaeusnek/cropspp/items/CppBerries.java#L27).

There’s actually a large amount of zs that can be migrated to code: I can start working on that

**Pull request closed without merging**
