### PR TITLE
Fixed a minor typo in Mundane Larch (2129) quest

### PR DESCRIPTION
**Pull request by Shadowsoftime99**
Someone pointed out this typo in the Discord, so I quick went and fixed it.

(There's also a bunch of whitespace changes in the diff, think it's from my editor. Let me know if these cause problems and I can try something else)

### CODE REVIEW

**Review by Dream-Master — CHANGES_REQUESTED** [review]
not fixing this file just change it in the Quest.jason file. The us lang fiele get automaticly corrected if the base file is right.

**Comment by Shadowsoftime99** [comment]
Fixed it there. I didn't see this quest in there at first but searching "calso" got me to it.

**Comment by Dream-Master** [comment]
@Shadowsoftime99 ok and now remove the changes on the us file. It will be automaticly added when the pr is merged. Thanks

**Comment by Shadowsoftime99** [comment]
I had already done so, unless you want me to revert my editor's whitespace changes as well?

**Comment by Dream-Master** [comment]
Yes the us json get auto update. Better revert it .

**Comment by Shadowsoftime99** [comment]
I'm reverting my commits and doing a fresh one, guess it closed this PR automatically. New one coming in a sec...

**Comment by Shadowsoftime99** [comment]
Good PR is https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/11335

**Pull request closed without merging**
